resources:
  - ../../../base/backend
  - namespace.yaml

namespace: therapist-app-main

configMapGenerator:
  - name: therapist-app-backend-config
    literals:
      - DB_HOST=192.168.1.147
      - DB_PORT=5432
      - DB_NAME=therapist_app_main_db
      - DB_USERNAME=therapist-user
      - DB_CREATE_OR_UPDATE=update
      - LOCAL_LLM_MODEL=gemma3:12b
      - LOCAL_LLM_URL=https://vllm-imrg.ifi.uzh.ch/vllm/v1/chat/completions
      - PATIENT_APP_URL=https://backend-patient-app-main.jonas-blum.ch
      - AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4.1
      - LLM_MAX_CHARACTERS=150000
      - MAX_CHARACTERS_PER_PDF=20000

secretGenerator:
  - name: therapist-app-backend-secret
    envs:
      - env.secrets
    type: Opaque

images:
  - name: jonasblum/image-to-be-replaced-depending-on-environment
    newName: jonasblum/therapist-app-backend-main
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-backend-ingress
    path: patch-ingress.json
