resources:
  - ../../../base/backend
  - ../namespace.yaml

namespace: therapist-app-main

images:
  - name: jonasblum/therapist-app-backend-main
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-backend-ingress
    path: patch-ingress.json
