/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChatCompletionResponseDTO } from '../models';
// @ts-ignore
import type { ChatCompletionWithConfigRequestDTO } from '../models';
/**
 * ChatControllerApi - axios parameter creator
 * @export
 */
export const ChatControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ChatCompletionWithConfigRequestDTO} chatCompletionWithConfigRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatWithConfig: async (chatCompletionWithConfigRequestDTO: ChatCompletionWithConfigRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatCompletionWithConfigRequestDTO' is not null or undefined
            assertParamExists('chatWithConfig', 'chatCompletionWithConfigRequestDTO', chatCompletionWithConfigRequestDTO)
            const localVarPath = `/api/chat/completions-with-config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatCompletionWithConfigRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatControllerApi - functional programming interface
 * @export
 */
export const ChatControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ChatCompletionWithConfigRequestDTO} chatCompletionWithConfigRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatWithConfig(chatCompletionWithConfigRequestDTO: ChatCompletionWithConfigRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatCompletionResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatWithConfig(chatCompletionWithConfigRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatControllerApi.chatWithConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatControllerApi - factory interface
 * @export
 */
export const ChatControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ChatCompletionWithConfigRequestDTO} chatCompletionWithConfigRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatWithConfig(chatCompletionWithConfigRequestDTO: ChatCompletionWithConfigRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<ChatCompletionResponseDTO> {
            return localVarFp.chatWithConfig(chatCompletionWithConfigRequestDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ChatControllerApi - interface
 * @export
 * @interface ChatControllerApi
 */
export interface ChatControllerApiInterface {
    /**
     * 
     * @param {ChatCompletionWithConfigRequestDTO} chatCompletionWithConfigRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatControllerApiInterface
     */
    chatWithConfig(chatCompletionWithConfigRequestDTO: ChatCompletionWithConfigRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<ChatCompletionResponseDTO>;

}

/**
 * ChatControllerApi - object-oriented interface
 * @export
 * @class ChatControllerApi
 * @extends {BaseAPI}
 */
export class ChatControllerApi extends BaseAPI implements ChatControllerApiInterface {
    /**
     * 
     * @param {ChatCompletionWithConfigRequestDTO} chatCompletionWithConfigRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatControllerApi
     */
    public chatWithConfig(chatCompletionWithConfigRequestDTO: ChatCompletionWithConfigRequestDTO, options?: RawAxiosRequestConfig) {
        return ChatControllerApiFp(this.configuration).chatWithConfig(chatCompletionWithConfigRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

