/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LogOutputDTO } from '../models';
/**
 * PatientLogControllerApi - axios parameter creator
 * @export
 */
export const PatientLogControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} patientId 
         * @param {string} logType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLogs: async (patientId: string, logType: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('listLogs', 'patientId', patientId)
            // verify required parameter 'logType' is not null or undefined
            assertParamExists('listLogs', 'logType', logType)
            const localVarPath = `/logs/patient/{patientId}/{logType}`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)))
                .replace(`{${"logType"}}`, encodeURIComponent(String(logType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PatientLogControllerApi - functional programming interface
 * @export
 */
export const PatientLogControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PatientLogControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} patientId 
         * @param {string} logType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listLogs(patientId: string, logType: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LogOutputDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listLogs(patientId, logType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PatientLogControllerApi.listLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PatientLogControllerApi - factory interface
 * @export
 */
export const PatientLogControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PatientLogControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} patientId 
         * @param {string} logType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLogs(patientId: string, logType: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<LogOutputDTO>> {
            return localVarFp.listLogs(patientId, logType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PatientLogControllerApi - interface
 * @export
 * @interface PatientLogControllerApi
 */
export interface PatientLogControllerApiInterface {
    /**
     * 
     * @param {string} patientId 
     * @param {string} logType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientLogControllerApiInterface
     */
    listLogs(patientId: string, logType: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<LogOutputDTO>>;

}

/**
 * PatientLogControllerApi - object-oriented interface
 * @export
 * @class PatientLogControllerApi
 * @extends {BaseAPI}
 */
export class PatientLogControllerApi extends BaseAPI implements PatientLogControllerApiInterface {
    /**
     * 
     * @param {string} patientId 
     * @param {string} logType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientLogControllerApi
     */
    public listLogs(patientId: string, logType: string, options?: RawAxiosRequestConfig) {
        return PatientLogControllerApiFp(this.configuration).listLogs(patientId, logType, options).then((request) => request(this.axios, this.basePath));
    }
}

