/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TherapistChatCompletionDTO } from '../models';
// @ts-ignore
import type { TherapistChatCompletionOutputDTO } from '../models';
/**
 * TherapistChatControllerApi - axios parameter creator
 * @export
 */
export const TherapistChatControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TherapistChatCompletionDTO} therapistChatCompletionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        therapistChat: async (therapistChatCompletionDTO: TherapistChatCompletionDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'therapistChatCompletionDTO' is not null or undefined
            assertParamExists('therapistChat', 'therapistChatCompletionDTO', therapistChatCompletionDTO)
            const localVarPath = `/therapist-chat/completions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(therapistChatCompletionDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TherapistChatControllerApi - functional programming interface
 * @export
 */
export const TherapistChatControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TherapistChatControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TherapistChatCompletionDTO} therapistChatCompletionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async therapistChat(therapistChatCompletionDTO: TherapistChatCompletionDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TherapistChatCompletionOutputDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.therapistChat(therapistChatCompletionDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TherapistChatControllerApi.therapistChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TherapistChatControllerApi - factory interface
 * @export
 */
export const TherapistChatControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TherapistChatControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {TherapistChatCompletionDTO} therapistChatCompletionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        therapistChat(therapistChatCompletionDTO: TherapistChatCompletionDTO, options?: RawAxiosRequestConfig): AxiosPromise<TherapistChatCompletionOutputDTO> {
            return localVarFp.therapistChat(therapistChatCompletionDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TherapistChatControllerApi - interface
 * @export
 * @interface TherapistChatControllerApi
 */
export interface TherapistChatControllerApiInterface {
    /**
     * 
     * @param {TherapistChatCompletionDTO} therapistChatCompletionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TherapistChatControllerApiInterface
     */
    therapistChat(therapistChatCompletionDTO: TherapistChatCompletionDTO, options?: RawAxiosRequestConfig): AxiosPromise<TherapistChatCompletionOutputDTO>;

}

/**
 * TherapistChatControllerApi - object-oriented interface
 * @export
 * @class TherapistChatControllerApi
 * @extends {BaseAPI}
 */
export class TherapistChatControllerApi extends BaseAPI implements TherapistChatControllerApiInterface {
    /**
     * 
     * @param {TherapistChatCompletionDTO} therapistChatCompletionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TherapistChatControllerApi
     */
    public therapistChat(therapistChatCompletionDTO: TherapistChatCompletionDTO, options?: RawAxiosRequestConfig) {
        return TherapistChatControllerApiFp(this.configuration).therapistChat(therapistChatCompletionDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

