resources:
  - ../../../base/frontend
  - namespace.yaml

namespace: therapist-app-main

images:
  - name: jonasblum/image-to-be-replaced-depending-on-environment
    newName: jonasblum/therapist-app-frontend-main
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-frontend-ingress
    path: patch-ingress.json
