resources:
  - ../../base/frontend

namespace: therapist-app-production

images:
  - name: jonasblum/therapist-app-frontend-production
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-frontend-ingress
    path: patch-ingress.json
