services:
  database:
    container_name: therapy-postgres
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: therapy-user
      POSTGRES_PASSWORD: therapy-password
      POSTGRES_DB: therapy-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: therapy-pgadmin
    depends_on:
      - database
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local
