openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://backend-patient-app-main.jonas-blum.ch
paths:
  /patients/onboarded:
    get:
      operationId: getOnboarded
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientOutputDTO'
          description: OK
      tags:
      - patient-controller
      x-accepts: '*/*'
    put:
      operationId: setOnboarded
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutOnboardedDTO'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - patient-controller
      x-content-type: application/json
      x-accepts: application/json
  /patients/language:
    get:
      operationId: getLanguage
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientOutputDTO'
          description: OK
      tags:
      - patient-controller
      x-accepts: '*/*'
    put:
      operationId: setLanguage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutLanguageDTO'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - patient-controller
      x-content-type: application/json
      x-accepts: application/json
  /patients/register:
    post:
      operationId: registerPatient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePatientDTO'
        required: true
      responses:
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientOutputDTO'
          description: Created
      tags:
      - patient-controller
      x-content-type: application/json
      x-accepts: '*/*'
  /patients/logout:
    post:
      operationId: logoutTherapist
      responses:
        "200":
          description: OK
      tags:
      - patient-controller
      x-accepts: application/json
  /patients/login:
    post:
      operationId: loginTherapist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPatientDTO'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientOutputDTO'
          description: OK
      tags:
      - patient-controller
      x-content-type: application/json
      x-accepts: '*/*'
  /patients/conversations:
    post:
      operationId: createConversation
      responses:
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreateConversationOutputDTO'
          description: Created
      tags:
      - conversation-controller
      x-accepts: '*/*'
  /patients/conversations/messages/{conversationId}:
    get:
      operationId: getAllMessages
      parameters:
      - explode: false
        in: path
        name: conversationId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompleteConversationOutputDTO'
          description: OK
      tags:
      - conversation-controller
      x-accepts: '*/*'
    post:
      operationId: sendMessage
      parameters:
      - explode: false
        in: path
        name: conversationId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessageDTO'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MessageOutputDTO'
          description: OK
      tags:
      - conversation-controller
      x-content-type: application/json
      x-accepts: '*/*'
  /patients/me:
    get:
      operationId: getCurrentlyLoggedInPatient
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientOutputDTO'
          description: OK
      tags:
      - patient-controller
      x-accepts: '*/*'
  /patients/conversations/{patientId}:
    get:
      operationId: nameConversationDTO
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/NameConversationOutputDTO'
                type: array
          description: OK
      tags:
      - conversation-controller
      x-accepts: '*/*'
  /:
    get:
      operationId: helloWorld
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      tags:
      - patient-app-application
      x-accepts: text/plain
components:
  schemas:
    PutOnboardedDTO:
      properties:
        onboarded:
          type: boolean
      type: object
    PutLanguageDTO:
      properties:
        language:
          type: string
      type: object
    CreatePatientDTO:
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    PatientOutputDTO:
      example:
        onboarded: true
        name: name
        description: description
        language: language
        id: id
        email: email
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        email:
          type: string
        language:
          type: string
        onboarded:
          type: boolean
      type: object
    LoginPatientDTO:
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    CreateConversationOutputDTO:
      example:
        id: id
      properties:
        id:
          type: string
      type: object
    CreateMessageDTO:
      properties:
        message:
          type: string
      type: object
    MessageOutputDTO:
      example:
        requestMessage: requestMessage
        conversationId: conversationId
        id: id
        responseMessage: responseMessage
        timestamp: timestamp
      properties:
        timestamp:
          type: string
        id:
          type: string
        conversationId:
          type: string
        responseMessage:
          type: string
        requestMessage:
          type: string
      type: object
    NameConversationOutputDTO:
      example:
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
      type: object
    CompleteConversationOutputDTO:
      example:
        name: name
        messages:
        - requestMessage: requestMessage
          conversationId: conversationId
          id: id
          responseMessage: responseMessage
          timestamp: timestamp
        - requestMessage: requestMessage
          conversationId: conversationId
          id: id
          responseMessage: responseMessage
          timestamp: timestamp
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        messages:
          items:
            $ref: '#/components/schemas/MessageOutputDTO'
          type: array
      type: object

