interface Resources {
  "de": {
    "yes": "Ja",
    "no": "Nein",
    "header": {
      "title": "Dies ist die Kopfzeile",
      "subtitle": "Dies sind die aktuellen Seiten:",
      "dashboard": "Dashboard-Seite",
      "register": "Registrierungsseite",
      "login": "Anmeldeseite",
      "patients": "Klientenübersichtsseite",
      "patient_detail": "Beispiel-Klientendetailseite für ID: \"{{id}}\"",
      "patient_create_bot": "Beispielseite zur Erstellung eines Klienten-Bots",
      "bot_edit": "Beispiel-Bot-Bearbeitungsseite für Bot-ID: \"{{id}}\"",
      "create_bot_template": "Seite zur Erstellung von Chatbot-Vorlagen",
      "edit_bot_template": "Chatbot-Vorlage für ID: \"{{id}}\" bearbeiten",
      "settings": "Einstellungsseite"
    },
    "footer": {
      "title": "Dies ist die Fusszeile",
      "note": "Fragen Sie Ihren persönlichen Assistenten..."
    },
    "settings": {
      "title": "Einstellungen",
      "language": "Sprache",
      "changePasswordTitle": "Passwort ändern",
      "newPassword": "Neues Passwort",
      "confirmNewPassword": "Neues Passwort bestätigen",
      "changePasswordButton": "Passwort ändern",
      "LOCAL_UZH": "UZH LLM (Privater Server)",
      "AZURE_OPENAI": "OpenAI LLM (Azure Cloud)",
      "llmModel": "LLM-Modell",
      "password_changed_success": "Passwort erfolgreich geändert",
      "description": {
        "LOCAL_UZH": "Das UZH LLM ist ein selbst-gehostetes Modell, das auf einem privaten Server betrieben wird. Ihr Gesprächsverlauf wird nicht gespeichert, was ein hohes Maß an Datenschutz und Sicherheit gewährleistet. Der Nachteil dieser erhöhten Privatsphäre ist, dass dieses Modell nicht so leistungsstark ist wie die cloud-gehostete Alternative. Daher können die Antworten weniger detailliert oder präzise sein.",
        "AZURE_OPENAI": "Das OpenAI LLM wird auf der Cloud-Infrastruktur von Microsoft Azure gehostet, wobei sich die Server in Schweden befinden. Obwohl diese Konfiguration sicher ist, unterscheidet sich das Datenschutzniveau von dem des selbst-gehosteten UZH-Modells. Der Hauptvorteil dieses Modells ist seine höhere Leistungsfähigkeit, was in der Regel zu umfassenderen und genaueren Antworten führt."
      }
    },
    "layout": {
      "dashboard": "Dashboard",
      "dashboards": "Dashboards",
      "general": "Allgemein",
      "settings": "Einstellungen",
      "patients": "Klienten",
      "list_patients": "Klientenliste",
      "create_patient": "Klient erstellen",
      "patient_details": "Klientendetails",
      "logout": "Abmelden",
      "overview": "Übersicht",
      "account": "Konto",
      "send": "Senden",
      "expand_AI_assistant": "KI-Assistent aufklappen",
      "close": "Schliessen"
    },
    "dashboard": {
      "home": "Startseite",
      "patient_register_success": "Klient erfolgreich registriert.",
      "register_new_patient": "Einen neuen Klienten registrieren",
      "add_patient": "Klient hinzufügen",
      "patients": "Klienten",
      "patient_id": "Klienten-ID",
      "unnamed_patient": "Unbenannter Klient",
      "no_patients_found": "Keine Klienten gefunden",
      "new_patient": "Neuer Klient",
      "enter_information_register_new_patient": "Geben Sie Informationen ein, um einen neuen Klienten zu registrieren.",
      "patient_name": "Name des Klienten",
      "patient_gender": "Geschlecht",
      "male": "Männlich",
      "female": "Weiblich",
      "other": "Divers",
      "patient_age": "Alter",
      "patient_phone_number": "Telefonnummer",
      "patient_email": "E-Mail",
      "patient_address": "Adresse",
      "patient_description": "Beschreibung des Klienten",
      "cancel": "Abbrechen",
      "register": "Registrieren",
      "rename": "Umbenennen",
      "clone": "Klonen",
      "delete": "Löschen",
      "save": "Speichern",
      "welcome_message": "Sie sind angemeldet als: ",
      "upload_file": "Datei hochladen",
      "chatbot_cloned_success": "Chatbot erfolgreich geklont.",
      "chatbot_deleted_success": "Chatbot erfolgreich gelöscht.",
      "create_bot": "Chatbot-Vorlage erstellen",
      "your_chatbot_templates": "Ihre Chatbot-Vorlagen",
      "unnamed_bot": "Unbenannter Bot",
      "no_welcome_message_set": "Keine Willkommensnachricht festgelegt",
      "no_chatbots_created_yet": "Noch keine Chatbots erstellt.",
      "role": "Rolle",
      "your_files": "Ihre Dateien"
    },
    "chatbot": {
      "chatbots": "Chatbots",
      "chatbot_created_success": "Chatbot erfolgreich erstellt.",
      "chatbot_updated_success": "Chatbot erfolgreich aktualisiert.",
      "chatbot_named_success": "Chatbot erfolgreich umbenannt.",
      "chatbot_cloned_success": "Chatbot erfolgreich geklont.",
      "chatbot_deleted_success": "Chatbot erfolgreich gelöscht.",
      "create_new_chatbot_template": "Neue Chatbot-Vorlage erstellen",
      "create_chatbot_from_template": "Chatbot aus Vorlage erstellen",
      "cannot_delete_last_template": "Letzte Vorlage kann nicht gelöscht werden.",
      "create_new_chatbot": "Neuen Chatbot erstellen",
      "new_bot": "Neuer Bot",
      "no_chatbots_created_yet": "Sie haben noch keine Chatbots erstellt.",
      "client_chatbot": "Klienten-Chatbot",
      "client_chatbots": "Klienten-Chatbots",
      "conversation_summary": "Gesprächszusammenfassung",
      "conversations_from": "Gespräche von",
      "conversation_private": "Dieses Gespräch des Klienten mit dem Chatbot ist privat.",
      "no_conversations_exist": "Keine Gespräche vorhanden.",
      "loading_conversation_summary": "Lade Gesprächszusammenfassung...",
      "what_would_you_like_to_name_your_bot": "Wie möchten Sie Ihren Bot nennen?",
      "enter_bot_name": "Bot-Namen eingeben",
      "rename_bot": "Bot umbenennen",
      "enter_new_name_for_bot": "Geben Sie den neuen Namen für Ihren Bot ein.",
      "enter_new_bot_name": "Neuen Bot-Namen eingeben",
      "template_not_leaded_yet": "Vorlage noch nicht geladen.",
      "chat_service_unavailable": "Chat-Dienst ist zurzeit nicht verfügbar.",
      "chatbot_configuration": "Chatbot-Konfiguration",
      "name": "Name",
      "role": "Rolle",
      "faq": "Häufig gestellte Fragen",
      "supportive": "Unterstützend",
      "counseling": "Beratung",
      "self_help": "Selbsthilfe",
      "undefined": "Undefiniert",
      "language": "Sprache",
      "english": "Englisch",
      "german": "Deutsch",
      "french": "Französisch",
      "spanish": "Spanisch",
      "chatbot_icon": "Chatbot-Symbol",
      "chatbot": "Chatbot",
      "robot": "Roboter",
      "person": "Person",
      "bulb": "Glühbirne",
      "book": "Buch",
      "voice": "Stimme",
      "none": "Keine",
      "male_voice": "Männliche Stimme",
      "female_voice": "Weibliche Stimme",
      "robotic_voice": "Roboterstimme",
      "gender": "Geschlecht",
      "neutral": "Neutral",
      "male": "Männlich",
      "female": "Weiblich",
      "conversation_tone": "Gesprächston",
      "friendly": "Freundlich",
      "formal": "Formell",
      "casual": "Lässig",
      "professional": "Professionell",
      "preconfigured_exercise": "Vorkonfigurierte Übung",
      "breathing_exercise": "Atemübung",
      "journaling": "Tagebuch führen",
      "relaxation_technique": "Entspannungstechnik",
      "additional_exercise": "Zusätzliche Übung",
      "meditation_practise": "Meditationspraxis",
      "cbt_example": "KVT-Beispiel",
      "animation": "Animation",
      "simple": "Einfach",
      "advanced": "Fortgeschritten",
      "welcome_message": "Willkommensnachricht",
      "chatbot_input_placeholder": "Platzhalter für Chatbot-Eingabe",
      "simulation": "Simulation",
      "you": "Sie",
      "type_your_message": "Geben Sie eine Nachricht ein...",
      "analytics": "Analyse",
      "total_chats": "Gesamtzahl der Chats (Threads)",
      "thread_id": "Thread-ID",
      "no_threads_found": "Keine Threads gefunden.",
      "template_files": "Vorlagendateien",
      "active_visiable_to_client": "Aktiv (für Klient sichtbar)",
      "save": "Speichern",
      "send": "Senden",
      "configuration": "Konfiguration",
      "sources": "Dokumente",
      "active": "Aktiv",
      "inactive": "Inaktiv"
    },
    "counseling_plan": {
      "counseling_plan": "Beratungsplan",
      "add_existing_exercise": "Bestehende Übung hinzufügen",
      "create_new_exercise": "Neue Übung erstellen",
      "exercise": "Übung",
      "title": "Titel",
      "exercises": "Übungen",
      "cancel": "Abbrechen",
      "start_date": "Startdatum",
      "end_date": "Enddatum",
      "duration": "Dauer",
      "weeks": "Wochen",
      "goals": "Ziele",
      "add_a_phase": "Phase hinzufügen",
      "phase_name": "Phasenname",
      "duration_in_weeks": "Dauer in Wochen",
      "create_phase": "Phase erstellen",
      "make_ai_generated_suggestion": "KI-generierten Vorschlag erstellen",
      "exercise_title": "Übungstitel",
      "exerciseDescription": "Beschreibung",
      "exerciseExplanation": "Erläuterung (für KI-Kontext)",
      "doEveryNDays": "Alle ... Tage wiederholen",
      "exercise_start": "Übungsbeginn",
      "add_a_goal": "Ziel hinzufügen",
      "goal_name": "Zielname",
      "goal_description": "Zielbeschreibung",
      "make_ai_generated_suggestion_for_goal": "KI-generierten Vorschlag für Ziel erstellen",
      "make_ai_generated_suggestion_for_phase": "KI-generierten Vorschlag für Phase erstellen",
      "make_ai_generated_suggestion_for_exercise": "KI-generierten Vorschlag für Übung erstellen",
      "create_goal": "Ziel erstellen",
      "counseling_start_date": "Startdatum der Beratung",
      "counseling_plan_phases": "Phasen des Beratungsplans",
      "phase_updated_success": "Phase erfolgreich aktualisiert",
      "update_phase": "Phase aktualisieren",
      "phase_goal_updated_success": "Phasenziel erfolgreich aktualisiert",
      "updateGoal": "Ziel aktualisieren",
      "phase_created_success": "Phase erfolgreich erstellt",
      "updated_successfully": "Erfolgreich aktualisiert",
      "exercise_added_success": "Übung erfolgreich hinzugefügt",
      "phase_deleted_success": "Phase erfolgreich gelöscht",
      "exercise_created_success": "Übung erfolgreich erstellt",
      "goal_created_success": "Ziel erfolgreich erstellt",
      "amountOfPhases": "Anzahl der Phasen",
      "goalsCompleted": "Ziele abgeschlossen",
      "goalsCompleted2": "Ziele abgeschlossen",
      "phase": "Phase",
      "completed": "abgeschlossen"
    },
    "exercise": {
      "upload_image": "Bild hochladen",
      "description": "Beschreibung",
      "add_input_field": "Eingabefeld hinzufügen",
      "description_of_input": "Beschreibung der Eingabe",
      "add_text": "Text hinzufügen",
      "text": "Text",
      "create_new_exercise": "Neue Übung erstellen",
      "exercise": "Übung",
      "exercises": "Übungen",
      "exercise_start": "Übungsbeginn",
      "duration_in_weeks": "Dauer in Wochen",
      "exercise_end": "Ende der Übung",
      "is_paused": "Pausiert",
      "is_active": "Aktiv",
      "is_currently_paused": "Derzeit pausiert",
      "is_exercise_paused": "Übung ist pausiert",
      "no_exercises_yet": "Sie haben noch keine Übungen hinzugefügt.",
      "no_exercise_components_yet": "Sie haben noch keine Übungskomponenten hinzugefügt.",
      "image": "Bild",
      "file": "Datei",
      "doEveryNDays": "Alle ... Tage wiederholen",
      "privateInput": "Privates Eingabefeld",
      "sharedInput": "Geteiltes Eingabefeld",
      "addPrivateInput": "Privates Eingabefeld hinzufügen",
      "addSharedInput": "Geteiltes Eingabefeld hinzufügen",
      "order": "Reihenfolge",
      "desciption_of_input": "Beschreibung der Eingabe",
      "title": "Titel",
      "exerciseDescription": "Beschreibung",
      "exerciseExplanation": "Erläuterung (für KI-Kontext)",
      "submit": "Senden",
      "cancel": "Abbrechen",
      "edit_exercise": "Übung bearbeiten",
      "exercise_components": "Übungskomponenten",
      "delete_exercise": "Übung löschen",
      "addYoutubeVideo": "YouTube-Video hinzufügen",
      "youtubeVideoUrl": "YouTube-Video-URL",
      "youtubeVideo": "YouTube-Video",
      "noUrlProvided": "Keine YouTube-URL angegeben",
      "invalidUrlProvided": "Ungültige YouTube-URL",
      "feedback": "Feedback",
      "startTime": "Startzeit",
      "endTime": "Endzeit",
      "moodsBefore": "Stimmung davor",
      "moodsAfter": "Stimmung danach",
      "editMode": "Bearbeitungsmodus",
      "viewMode": "Ansichtsmodus",
      "youtubeDescription": "Beschreibung des Videos",
      "exercise_created_successfully": "Übung erfolgreich erstellt",
      "exercise_updated_successfully": "Übung erfolgreich aktualisiert",
      "exercise_deleted_successfully": "Übung erfolgreich gelöscht",
      "component_created_successfully": "Übungskomponente erfolgreich erstellt",
      "component_updated_successfully": "Übungskomponente erfolgreich aktualisiert",
      "component_deleted_successfully": "Übungskomponente erfolgreich gelöscht",
      "exercise_removed_successfully": "Übung erfolgreich entfernt",
      "goal_removed_successfully": "Ziel erfolgreich entfernt",
      "client_feedback": "Klienten-Feedback",
      "no_client_feedback": "Der Klient hat noch kein Feedback zu dieser Übung gegeben.",
      "privateInputTooltip": "Dieses private Eingabefeld ermöglicht es dem Klienten, seine eigenen Gedanken festzuhalten, die nicht mit dem Coach geteilt werden.",
      "sharedInputTooltip": "Dieses geteilte Eingabefeld ermöglicht es dem Klienten, seine eigenen Gedanken festzuhalten, die für den Coach sichtbar sein werden.",
      "completions": "Übungsabschlüsse",
      "moodtracking": {
        "very_unpleasant": "sehr unangenehm",
        "unpleasant": "unangenehm",
        "neutral": "neutral",
        "pleasant": "angenehm",
        "very_pleasant": "sehr angenehm"
      }
    },
    "not_found": {
      "title": "404 - Seite nicht gefunden",
      "message": "Hoppla! Die von Ihnen gesuchte Seite existiert nicht."
    },
    "patient_detail": {
      "message": "Dies ist die Detailseite des Klienten mit der ID",
      "view_client_interactions": "Klienteninteraktionen anzeigen",
      "client": "Klient",
      "email_client_app": "E-Mail (für Login in der Klienten-App)",
      "initial_password_client_app": "Initialpasswort (für Login in der Klienten-App)",
      "client_app_link": "Link zur Klienten-App",
      "age": "Alter",
      "gender": "Geschlecht",
      "phone": "Telefon",
      "address": "Adresse",
      "date_of_admission": "Aufnahmedatum",
      "view_more_details": "Weitere Details anzeigen",
      "loading_patient_data": "Lade Klientendaten...",
      "counseling_plan": "Beratungsplan",
      "go_to_counseling_plan": "Zum Beratungsplan gehen",
      "current_phase": "Aktuelle Phase",
      "currently_no_phase_is_active": "Derzeit ist keine Phase aktiv.",
      "create_a_new_chatbot": "Einen neuen Chatbot erstellen",
      "please_enter_name_for_chatbot": "Bitte geben Sie einen Namen für Ihren neuen Chatbot ein",
      "chatbot_name": "Chatbot-Name",
      "create_bot": "Bot erstellen",
      "files_visible_to_client": "Für den Klienten sichtbare Dateien",
      "files_visible_only_to_coach": "Nur für den Coach sichtbare Dateien",
      "no_files_uploaded_yet": "Sie haben noch keine Dateien hochgeladen.",
      "file_name": "Dateiname",
      "actions": "Aktionen",
      "download": "Herunterladen",
      "delete": "Löschen",
      "edit": "Bearbeiten",
      "save_changes": "Änderungen speichern",
      "file_upload_success": "Datei erfolgreich hochgeladen",
      "file_delete_success": "Datei erfolgreich gelöscht",
      "manage_tests": "GAD7-Tests verwalten"
    },
    "patient_interactions": {
      "interaction_type": "Interaktionstyp",
      "start_date": "Startdatum",
      "end_date": "Enddatum",
      "time": "Uhrzeit",
      "date": "Datum",
      "last_week": "Letzte Woche",
      "last_two_weeks": "Letzte 2 Wochen",
      "last_three_weeks": "Letzte 3 Wochen",
      "loading": "Lade Daten der Klienteninteraktionen...",
      "fetch_error": "Fehler beim Abrufen der Klienteninteraktionsdaten.",
      "no_data": "Keine Klienten-Protokolldaten verfügbar.",
      "interactions": "Interaktionen",
      "export_to_csv": "Nach CSV exportieren",
      "log_types": {
        "journal_creation": "Tagebucherstellung",
        "journal_update": "Tagebuchaktualisierung",
        "exercise_start": "Übungsbeginn",
        "exercise_completion": "Übungsabschluss",
        "exercise_update": "Übungsaktualisierung",
        "general_conversation_creation": "Erstellung eines allgemeinen Gesprächs",
        "general_conversation_name_update": "Aktualisierung des Namens eines allgemeinen Gesprächs",
        "general_conversation_message_creation": "Erstellung einer Nachricht in einem allgemeinen Gespräch",
        "document_conversation_message_creation": "Erstellung einer Nachricht in einem Dokumentengespräch",
        "exercise_conversation_message_creation": "Erstellung einer Nachricht in einem Übungsgespräch",
        "journal_conversation_message_creation": "Erstellung einer Nachricht in einem Tagebuchgespräch",
        "chatbot_icon_update": "Aktualisierung des Chatbot-Symbols",
        "harmful_content_detected": "Schädlicher Inhalt erkannt",
        "document_read": "Dokument gelesen",
        "psychological_test_completed": "Psychologischer Test abgeschlossen"
      }
    },
    "patient_create": {
      "title": "Seite zur Erstellung eines neuen Klienten",
      "new_patient": "Neuer Klient",
      "create_patient": "Klient erstellen",
      "patient_name": "Name des Klienten",
      "patient_age": "Alter",
      "patient_gender": "Geschlecht",
      "male": "Männlich",
      "female": "Weiblich",
      "other": "Divers",
      "patient_marital_status": "Familienstand",
      "patient_religion": "Religion",
      "patient_education": "Bildung",
      "patient_occupation": "Beruf",
      "patient_income": "Einkommen",
      "patient_address": "Adresse",
      "patient_phone": "Telefonnummer",
      "patient_email": "E-Mail",
      "patient_date_of_admission": "Aufnahmedatum",
      "register": "Registrieren",
      "cancel": "Abbrechen",
      "complaint": "Beschwerde",
      "main_complaints": "Hauptbeschwerden",
      "history_of_present_illness": "Anamnese der aktuellen Erkrankung",
      "hpi_duration": "Dauer",
      "hpi_onset": "Beginn",
      "onset_abrupt": "Plötzlich",
      "onset_acute": "Akut",
      "onset_subacute": "Subakut",
      "onset_insidious": "Schleichend",
      "hpi_course": "Verlauf",
      "hpi_course_continuous": "Kontinuierlich",
      "hpi_course_episodic": "Episodisch",
      "hpi_course_fluctuating": "Fluktuierend",
      "hpi_course_deteriorating": "Verschlechternd",
      "hpi_course_improving": "Verbessernd",
      "hpi_course_unclear": "Unklar",
      "hpi_precipitating_factors": "Auslösende Faktoren",
      "hpi_aggravating_relieving": "Verschlimmernde und lindernde Faktoren",
      "hpi_aggravating_relieving_placeholder": "Was macht es besser oder schlechter?",
      "hpi_timeline": "Zeitachse",
      "hpi_timeline_placeholder": "Beschreiben Sie, wie sich die Symptome im Laufe der Zeit entwickelt haben.",
      "hpi_advanced_details": "Erweiterte Anamnese-Details",
      "hpi_disturbances": "Störungen von Schlaf, Appetit, Energie usw.",
      "hpi_disturbances_placeholder": "z. B. Schlaflosigkeit, Müdigkeit, Gewichtsveränderung",
      "hpi_suicidal_ideation": "Suizidgedanken oder -verhalten",
      "yes_no_explanation": "Ja/Nein mit kurzer Erklärung",
      "hpi_negative_history": "Relevante Negativanamnese",
      "hpi_negative_history_placeholder": "Erwähnen Sie Zustände, die nicht vorhanden sind",
      "history_present_illness": "Anamnese der aktuellen Erkrankung",
      "hpi_general_info": "Allgemeine Informationen",
      "hpi_onset_abrupt": "Plötzlich",
      "hpi_onset_acute": "Akut",
      "hpi_onset_subacute": "Subakut",
      "hpi_onset_insidious": "Schleichend",
      "hpi_symptom_timeline": "Symptom-Zeitachse",
      "add_another_complaint": "Weitere Beschwerde hinzufügen",
      "treatment_history": "Behandlungsverlauf",
      "treatment_past": "Frühere Behandlungen",
      "treatment_current": "Aktuelle Behandlungen",
      "past_history": "Vorgeschichte",
      "past_medical": "Medizinische Vorgeschichte",
      "past_psych": "Psychiatrische Vorgeschichte",
      "family_history": "Familienanamnese",
      "family_illness": "Familiäre Erkrankungen",
      "family_social": "Sozialer Hintergrund der Familie",
      "personal_history": "Persönliche Anamnese",
      "personal_perinatal": "Perinatale Anamnese",
      "personal_childhood": "Kindheitsanamnese",
      "personal_education": "Bildungsanamnese",
      "personal_play": "Spiel- und Sozialanamnese",
      "personal_adolescence": "Jugendanamnese",
      "personal_puberty": "Pubertäts- und Sexualanamnese",
      "personal_obstetric": "Geburtshilfliche Anamnese",
      "personal_occupational": "Berufsanamnese",
      "personal_marital": "Ehe- und Beziehungsanamnese",
      "personal_premorbid": "Prämorbide Persönlichkeit",
      "patient_register_success": "Klient erfolgreich registriert.",
      "patient_register_failed": "Registrierung des Klienten fehlgeschlagen. Bitte versuchen Sie es erneut."
    },
    "register": {
      "welcome": "Willkommen in der Coach-App",
      "register_therapist": "Als neuer Coach registrieren",
      "email": "E-Mail",
      "password": "Passwort",
      "register": "Registrieren",
      "go_login": "Stattdessen zur Anmeldung",
      "success": "Erfolgreich registriert"
    },
    "login": {
      "welcome": "Willkommen in der Coach-App",
      "login_therapist": "Als Coach anmelden",
      "email": "E-Mail",
      "password": "Passwort",
      "login": "Anmelden",
      "go_registration": "Stattdessen zur Registrierung",
      "success": "Erfolgreiche Anmeldung"
    },
    "meetings": {
      "meetings": "Termine",
      "meeting_start": "Beginn des Termins",
      "meeting_end": "Ende des Termins",
      "meeting_location": "Ort des Termins",
      "no_meetings_yet": "Sie haben noch keine geplanten Termine.",
      "duration": "Dauer",
      "duration_in_minutes": "Dauer in Minuten",
      "minutes": "Minuten",
      "location": "Ort",
      "create_meeting": "Termin erstellen",
      "create_new_note": "Neue Notiz erstellen",
      "transcribe_meeting": "Gespräch transkribieren",
      "meeting_transcription": "Gesprächstranskription",
      "new_note": "Neue Notiz",
      "title": "Titel",
      "language": "Sprache",
      "content": "Inhalt (Tippen oder Sprechen)",
      "speak_or_type_here": "Sprechen oder tippen Sie hier...",
      "start_listening": "Zuhören starten",
      "listening": "Höre zu...",
      "listening_speak_into_microphone": "Höre zu... Sprechen Sie in Ihr Mikrofon.",
      "stop_listening": "Zuhören beenden",
      "no_notes_yet": "Sie haben noch keine Notizen.",
      "delete_meeting": "Termin löschen",
      "browser_compatibility": "Browser-Kompatibilität",
      "web_search_api_not_supported": "Die Web Speech API wird von Ihrem Browser nicht unterstützt. Bitte versuchen Sie es mit Chrome oder Edge für die beste Erfahrung.",
      "is_past": "Liegt in der Vergangenheit",
      "error": {
        "error": "Fehler",
        "no_speech_detected": "Keine Sprache erkannt. Bitte versuchen Sie, etwas lauter oder deutlicher zu sprechen.",
        "microphone_not_available": "Mikrofon nicht verfügbar oder Berechtigung verweigert. Bitte überprüfen Sie Ihre Mikrofoneinstellungen und Browser-Berechtigungen.",
        "not_allowed": "Die Berechtigung zur Nutzung des Mikrofons wurde verweigert oder nicht erteilt. Bitte erlauben Sie den Mikrofonzugriff in Ihren Browser-Einstellungen."
      },
      "save": "Speichern",
      "cancel": "Abbrechen",
      "CONFIRMED": "Bestätigt",
      "CANCELLED": "Abgesagt",
      "PENDING": "Ausstehend",
      "editMeeting": "Termin bearbeiten",
      "meetingStatus": "Terminstatus",
      "yourNotes": "Ihre Notizen",
      "meeting_created_successfully": "Termin erfolgreich erstellt",
      "meeting_deleted_successfully": "Termin erfolgreich gelöscht",
      "meeting_updated_successfully": "Termin erfolgreich aktualisiert",
      "note_created_successfully": "Notiz zum Termin erfolgreich erstellt",
      "note_updated_successfully": "Notiz zum Termin erfolgreich aktualisiert",
      "note_deleted_successfully": "Notiz zum Termin erfolgreich gelöscht",
      "notes_summary": "Zusammenfassung der Notizen"
    },
    "gad7test": {
      "title": "GAD-7-Bewertung",
      "gad7tests": "GAD-7-Tests",
      "completed_gad7tests": "Abgeschlossene GAD-7-Tests",
      "manage_description": "Legen Sie fest, wie oft der Klient den GAD-7-Test durchführen soll (in Tagen):",
      "start_date": "Startdatum",
      "doEveryNDays": "Alle ... Tage",
      "schedule_summary": "Mit diesen Einstellungen wird der Patient den GAD7-Test alle {{days}} Tage ab dem {{date}} ausfüllen.",
      "date": "Datum",
      "description": "Wie oft fühlten Sie sich während der letzten 2 Wochen durch die folgenden Probleme belästigt?",
      "question1": "Nervosität, Ängstlichkeit oder Anspannung.",
      "question2": "Nicht in der Lage sein, das Sorgen zu stoppen oder zu kontrollieren.",
      "question3": "Sich zu viele Sorgen über verschiedene Dinge machen.",
      "question4": "Schwierigkeiten, sich zu entspannen.",
      "question5": "So unruhig sein, dass es schwerfällt, stillzusitzen.",
      "question6": "Leicht verärgert oder gereizt werden.",
      "question7": "Sich fürchten, als ob etwas Schreckliches passieren könnte.",
      "total_score": "Gesamtpunktzahl",
      "cancel": "Abbrechen",
      "save_changes": "Änderungen speichern",
      "no_tests_yet": "Der Klient hat noch keine GAD-7-Tests ausgefüllt.",
      "answers": {
        "not_at_all": "Überhaupt nicht",
        "several_days": "An mehreren Tagen",
        "more_than_half_the_days": "An mehr als der Hälfte der Tage",
        "nearly_everyday": "Beinahe jeden Tag"
      }
    },
    "pages": {
      "home": "Startseite",
      "login": "Anmelden",
      "logout": "Abmelden",
      "registration": "Registrierung",
      "settings": "Einstellungen",
      "patients": {
        "create": "Neuen Klienten registrieren",
        "details": "Klientendetails",
        "conversations": "Gesprächszusammenfassung",
        "interactions": "Klienteninteraktionen",
        "details_update": "Klient wird aktualisiert"
      },
      "chatbot": {
        "create": "Neuen Chatbot erstellen",
        "details": "Chatbot-Details"
      },
      "meetings": {
        "create": "Neuen Termin erstellen",
        "details": "Termindetails"
      },
      "gad7": {
        "manage": "GAD-7 Tests verwalten"
      },
      "exercises": {
        "create": "Übung erstellen",
        "details": "Übungsdetails"
      },
      "chatbot_templates": {
        "create": "Neue Chatbot-Vorlage erstellen",
        "details": "Details der Chatbot-Vorlage"
      },
      "counseling_plan": {
        "details": "Beratungsplan"
      },
      "not_found": "Nicht gefunden",
      "therapist_chatbot": "Coach-Chatbot"
    },
    "files": {
      "download_success": "Datei erfolgreich heruntergeladen"
    }
  },
  "en": {
    "yes": "Yes",
    "no": "No",
    "header": {
      "title": "This is the header",
      "subtitle": "These are the current pages:",
      "dashboard": "Dashboard Page",
      "register": "Register Page",
      "login": "Login Page",
      "patients": "Client Overview Page",
      "patient_detail": "Example Client Detail Page for ID: \"{{id}}\"",
      "patient_create_bot": "Example Client Create Bot Page",
      "bot_edit": "Example Bot Edit Page for Bot ID: \"{{id}}\"",
      "create_bot_template": "Create Chatbot Template Page",
      "edit_bot_template": "Edit Chatbot Template for ID: \"{{id}}\"",
      "settings": "Settings Page"
    },
    "footer": {
      "title": "This is the footer",
      "note": "Ask your personal assistant..."
    },
    "settings": {
      "title": "Settings",
      "language": "Language",
      "changePasswordTitle": "Change password",
      "newPassword": "New password",
      "confirmNewPassword": "Confirm new password",
      "changePasswordButton": "Change password",
      "LOCAL_UZH": "UZH LLM (Private Server)",
      "AZURE_OPENAI": "OpenAI LLM (Azure Cloud)",
      "llmModel": "LLM Model",
      "password_changed_success": "Successfully changed password",
      "description": {
        "LOCAL_UZH": "The UZH LLM is a self-hosted model running on a private server. Your conversation history is not stored, ensuring a high level of data privacy and security. The trade-off for this enhanced privacy is that this model is not as powerful as the cloud-hosted alternative. As a result, its answers may be less detailed or accurate.",
        "AZURE_OPENAI": "The OpenAI LLM is hosted on Microsoft Azure's cloud infrastructure, with servers located in Sweden. While this setup is secure, the data privacy level differs from the self-hosted UZH model. The primary advantage of this model is its superior performance, which generally results in more comprehensive and accurate answers."
      }
    },
    "layout": {
      "dashboard": "Dashboard",
      "dashboards": "Dashboards",
      "general": "General",
      "settings": "Settings",
      "patients": "Clients",
      "list_patients": "List Clients",
      "create_patient": "Create Client",
      "patient_details": "Client Details",
      "logout": "Log Out",
      "overview": "Overview",
      "account": "Account",
      "send": "Send",
      "expand_AI_assistant": "Expand AI Assistant",
      "close": "Close"
    },
    "dashboard": {
      "home": "Home",
      "patient_register_success": "Client registered successfully.",
      "register_new_patient": "Register a new client",
      "add_patient": "Add Client",
      "patients": "Clients",
      "patient_id": "Client ID",
      "unnamed_patient": "Unnamed Client",
      "no_patients_found": "No clients found",
      "new_patient": "New Client",
      "enter_information_register_new_patient": "Enter information to register a new client.",
      "patient_name": "Client Name",
      "patient_gender": "Gender",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_age": "Age",
      "patient_phone_number": "Phone Number",
      "patient_email": "Email",
      "patient_address": "Address",
      "patient_description": "Client Description",
      "cancel": "Cancel",
      "register": "Register",
      "rename": "Rename",
      "clone": "Clone",
      "delete": "Delete",
      "save": "Save",
      "welcome_message": "You are logged in as: ",
      "upload_file": "Upload File",
      "chatbot_cloned_success": "Chatbot cloned successfully.",
      "chatbot_deleted_success": "Chatbot deleted successfully.",
      "create_bot": "Create Chatbot Template",
      "your_chatbot_templates": "Your Chatbot Templates",
      "unnamed_bot": "Unnamed Bot",
      "no_welcome_message_set": "No welcome message set",
      "no_chatbots_created_yet": "No chatbots created yet.",
      "role": "Role",
      "your_files": "Your Files"
    },
    "chatbot": {
      "chatbots": "Chatbots",
      "chatbot_created_success": "Chatbot created successfully.",
      "chatbot_updated_success": "Chatbot updated successfully.",
      "chatbot_named_success": "Chatbot renamed successfully.",
      "chatbot_cloned_success": "Chatbot cloned successfully.",
      "chatbot_deleted_success": "Chatbot deleted successfully.",
      "create_new_chatbot_template": "Create new chatbot template",
      "create_chatbot_from_template": "Create Chatbot from Template",
      "cannot_delete_last_template": "Last template cannot be deleted.",
      "create_new_chatbot": "Create New Chatbot",
      "new_bot": "New Bot",
      "no_chatbots_created_yet": "You haven't created any chatbots yet.",
      "client_chatbot": "Client Chatbot",
      "client_chatbots": "Client Chatbots",
      "conversation_summary": "Conversation Summary",
      "conversations_from": "Conversations from",
      "conversation_private": "This conversation of the client with the chatbot is private",
      "no_conversations_exist": "No Conversations Exist",
      "loading_conversation_summary": "Loading conversation summary...",
      "what_would_you_like_to_name_your_bot": "What would you like to name your bot?",
      "enter_bot_name": "Enter bot name",
      "rename_bot": "Rename Bot",
      "enter_new_name_for_bot": "Enter the new name for your bot.",
      "enter_new_bot_name": "Enter new bot name",
      "template_not_leaded_yet": "Template not loaded yet.",
      "chat_service_unavailable": "Chat service is currently unavailable.",
      "chatbot_configuration": "Chatbot Configuration",
      "name": "Name",
      "role": "Role",
      "faq": "FAQ",
      "supportive": "Supportive",
      "counseling": "Counseling",
      "self_help": "Self-Help",
      "undefined": "Undefined",
      "language": "Language",
      "english": "English",
      "german": "German",
      "french": "French",
      "spanish": "Spanish",
      "chatbot_icon": "Chatbot Icon",
      "chatbot": "Chatbot",
      "robot": "Robot",
      "person": "Person",
      "bulb": "Bulb",
      "book": "Book",
      "voice": "Voice",
      "none": "None",
      "male_voice": "Male Voice",
      "female_voice": "Female Voice",
      "robotic_voice": "Robotic Voice",
      "gender": "Gender",
      "neutral": "Neutral",
      "male": "Male",
      "female": "Female",
      "conversation_tone": "Conversation Tone",
      "friendly": "Friendly",
      "formal": "Formal",
      "casual": "Casual",
      "professional": "Professional",
      "preconfigured_exercise": "Pre-configured Exercise",
      "breathing_exercise": "Breathing Exercise",
      "journaling": "Journaling",
      "relaxation_technique": "Relaxation Technique",
      "additional_exercise": "Additional Exercise",
      "meditation_practise": "Meditation Practice",
      "cbt_example": "CBT Example",
      "animation": "Animation",
      "simple": "Simple",
      "advanced": "Advanced",
      "welcome_message": "Welcome Message",
      "chatbot_input_placeholder": "Chatbot Input Placeholder",
      "simulation": "Simulation",
      "you": "You",
      "type_your_message": "Type a message...",
      "analytics": "Analytics",
      "total_chats": "Total Chats (Threads)",
      "thread_id": "Thread ID",
      "no_threads_found": "No threads found.",
      "template_files": "Template Files",
      "active_visiable_to_client": "Active (Visible to Client)",
      "save": "Save",
      "send": "Send",
      "configuration": "Configuration",
      "sources": "Sources",
      "active": "Active",
      "inactive": "Inactive"
    },
    "counseling_plan": {
      "counseling_plan": "Counseling Plan",
      "add_existing_exercise": "Add Existing Exercise",
      "create_new_exercise": "Create New Exercise",
      "exercise": "Exercise",
      "title": "Title",
      "exercises": "Exercises",
      "cancel": "Cancel",
      "start_date": "Start Date",
      "end_date": "End Date",
      "duration": "Duration",
      "weeks": "Weeks",
      "goals": "Goals",
      "add_a_phase": "Add a Phase",
      "phase_name": "Phase Name",
      "duration_in_weeks": "Duration in Weeks",
      "create_phase": "Create Phase",
      "make_ai_generated_suggestion": "Make AI-generated suggestion",
      "exercise_title": "Exercise Title",
      "exerciseDescription": "Description",
      "exerciseExplanation": "Explanation (for AI context)",
      "doEveryNDays": "Repeat every ... days",
      "exercise_start": "Exercise Start",
      "add_a_goal": "Add a Goal",
      "goal_name": "Goal Name",
      "goal_description": "Goal Description",
      "make_ai_generated_suggestion_for_goal": "Make AI-generated suggestion for goal",
      "make_ai_generated_suggestion_for_phase": "Make AI-generated suggestion for phase",
      "make_ai_generated_suggestion_for_exercise": "Make AI-generated suggestion for exercise",
      "create_goal": "Create Goal",
      "counseling_start_date": "Counseling Start Date",
      "counseling_plan_phases": "Counseling Plan Phases",
      "phase_updated_success": "Successfully updated phase",
      "update_phase": "Update phase",
      "phase_goal_updated_success": "Successfully updated phase goal",
      "updateGoal": "Update goal",
      "phase_created_success": "Successfully created phase",
      "updated_successfully": "Successfully updated",
      "exercise_added_success": "Successfully added exercise",
      "phase_deleted_success": "Successfully deleted phase",
      "exercise_created_success": "Successfully created exercise",
      "goal_created_success": "Successfully created goal",
      "amountOfPhases": "Amount of phases",
      "goalsCompleted": "Goals completed",
      "goalsCompleted2": "goals completed",
      "phase": "Phase",
      "completed": "completed"
    },
    "exercise": {
      "upload_image": "Upload Image",
      "description": "Description",
      "add_input_field": "Add Input Field",
      "description_of_input": "Description of Input",
      "add_text": "Add Text",
      "text": "Text",
      "create_new_exercise": "Create New Exercise",
      "exercise": "Exercise",
      "exercises": "Exercises",
      "exercise_start": "Exercise Start",
      "duration_in_weeks": "Duration in Weeks",
      "exercise_end": "Exercise End",
      "is_paused": "Is Paused",
      "is_active": "Is Active",
      "is_currently_paused": "Is Currently Paused",
      "is_exercise_paused": "Is Exercise Paused",
      "no_exercises_yet": "You haven't added any exercises yet.",
      "no_exercise_components_yet": "You haven't added any exercise components yet.",
      "image": "Image",
      "file": "File",
      "doEveryNDays": "Repeat every ... days",
      "privateInput": "Private Input Field",
      "sharedInput": "Shared Input Field",
      "addPrivateInput": "Add Private Input Field",
      "addSharedInput": "Add Shared Input Field",
      "order": "Order",
      "desciption_of_input": "Description of Input",
      "title": "Title",
      "exerciseDescription": "Description",
      "exerciseExplanation": "Explanation (for AI context)",
      "submit": "Submit",
      "cancel": "Cancel",
      "edit_exercise": "Edit Exercise",
      "exercise_components": "Exercise Components",
      "delete_exercise": "Delete Exercise",
      "addYoutubeVideo": "Add YouTube Video",
      "youtubeVideoUrl": "YouTube Video URL",
      "youtubeVideo": "YouTube Video",
      "noUrlProvided": "No YouTube URL provided",
      "invalidUrlProvided": "Invalid YouTube URL",
      "feedback": "Feedback",
      "startTime": "Start Time",
      "endTime": "End Time",
      "moodsBefore": "Mood Before",
      "moodsAfter": "Mood After",
      "editMode": "Edit Mode",
      "viewMode": "View Mode",
      "youtubeDescription": "Description of Video",
      "exercise_created_successfully": "Successfully created exercise",
      "exercise_updated_successfully": "Successfully updated exercise",
      "exercise_deleted_successfully": "Successfully deleted exercise",
      "component_created_successfully": "Successfully created exercise component",
      "component_updated_successfully": "Successfully updated exercise component",
      "component_deleted_successfully": "Successfully deleted exercise component",
      "exercise_removed_successfully": "Successfully removed exercise",
      "goal_removed_successfully": "Successfully removed goal",
      "client_feedback": "Client Feedback",
      "no_client_feedback": "The client has not provided any feedback for this exercise yet.",
      "privateInputTooltip": "This private input field components lets the client write down their own thoughts which will not be shared with the coach.",
      "sharedInputTooltip": "This shared input field component lets the client write down their own thoughts which will be visible for the coach.",
      "completions": "Exercise Completions",
      "moodtracking": {
        "very_unpleasant": "very unpleasant",
        "unpleasant": "unpleasant",
        "neutral": "neutral",
        "pleasant": "pleasant",
        "very_pleasant": "very pleasant"
      }
    },
    "not_found": {
      "title": "404 - Page Not Found",
      "message": "Oops! The page you're looking for doesn't exist."
    },
    "patient_detail": {
      "message": "This is the client detail page of client with ID",
      "view_client_interactions": "View Client Interactions",
      "client": "Client",
      "email_client_app": "Email (for Login in Client App)",
      "initial_password_client_app": "Initial Password (for Login in Client App)",
      "client_app_link": "Client App Link",
      "age": "Age",
      "gender": "Gender",
      "phone": "Phone",
      "address": "Address",
      "date_of_admission": "Date of Admission",
      "view_more_details": "View more details",
      "loading_patient_data": "Loading client data...",
      "counseling_plan": "Counseling Plan",
      "go_to_counseling_plan": "Go to Counseling Plan",
      "current_phase": "Current Phase",
      "currently_no_phase_is_active": "Currently no phase is active.",
      "create_a_new_chatbot": "Create a new Chatbot",
      "please_enter_name_for_chatbot": "Please enter a name for your new chatbot",
      "chatbot_name": "Chatbot Name",
      "create_bot": "Create Bot",
      "files_visible_to_client": "Files visible to client",
      "files_visible_only_to_coach": "Files visible only to coach",
      "no_files_uploaded_yet": "You haven't uploaded any files yet.",
      "file_name": "File Name",
      "actions": "Actions",
      "download": "Download",
      "delete": "Delete",
      "edit": "Edit",
      "save_changes": "Save",
      "file_upload_success": "Successfully uploaded file",
      "file_delete_success": "Successfully deleted file",
      "manage_tests": "Manage GAD7 Tests"
    },
    "patient_interactions": {
      "interaction_type": "Interaction Type",
      "start_date": "Start Date",
      "end_date": "End Date",
      "time": "Time",
      "date": "Date",
      "last_week": "Last Week",
      "last_two_weeks": "Last 2 Weeks",
      "last_three_weeks": "Last 3 Weeks",
      "loading": "Loading client interactions data...",
      "fetch_error": "Error fetching client interactions data.",
      "no_data": "No client log data available.",
      "interactions": "Interactions",
      "export_to_csv": "Export to CSV",
      "log_types": {
        "journal_creation": "Journal Creation",
        "journal_update": "Journal Update",
        "exercise_start": "Exercise Start",
        "exercise_completion": "Exercise Completion",
        "exercise_update": "Exercise Update",
        "general_conversation_creation": "General Conversation Creation",
        "general_conversation_name_update": "General Conversation Name Update",
        "general_conversation_message_creation": "General Conversation Message Creation",
        "document_conversation_message_creation": "Document Conversation Message Creation",
        "exercise_conversation_message_creation": "Exercise Conversation Message Creation",
        "journal_conversation_message_creation": "Journal Conversation Message Creation",
        "chatbot_icon_update": "Chatbot Icon Update",
        "harmful_content_detected": "Harmful Content",
        "document_read": "Document Read",
        "psychological_test_completed": "Psychological Test Completed"
      }
    },
    "patient_create": {
      "title": "This is the page to create a new client",
      "new_patient": "New Client",
      "create_patient": "Create Client",
      "patient_name": "Client Name",
      "patient_age": "Age",
      "patient_gender": "Gender",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_marital_status": "Marital Status",
      "patient_religion": "Religion",
      "patient_education": "Education",
      "patient_occupation": "Occupation",
      "patient_income": "Income",
      "patient_address": "Address",
      "patient_phone": "Phone Number",
      "patient_email": "Email",
      "patient_date_of_admission": "Date of Admission",
      "register": "Register",
      "cancel": "Cancel",
      "complaint": "Complaint",
      "main_complaints": "Main Complaints",
      "history_of_present_illness": "History of Present Illness",
      "hpi_duration": "Duration",
      "hpi_onset": "Onset",
      "onset_abrupt": "Abrupt",
      "onset_acute": "Acute",
      "onset_subacute": "Subacute",
      "onset_insidious": "Insidious",
      "hpi_course": "Course",
      "hpi_course_continuous": "Continuous",
      "hpi_course_episodic": "Episodic",
      "hpi_course_fluctuating": "Fluctuating",
      "hpi_course_deteriorating": "Deteriorating",
      "hpi_course_improving": "Improving",
      "hpi_course_unclear": "Unclear",
      "hpi_precipitating_factors": "Precipitating Factors",
      "hpi_aggravating_relieving": "Aggravating and Relieving Factors",
      "hpi_aggravating_relieving_placeholder": "What makes it better or worse?",
      "hpi_timeline": "Timeline",
      "hpi_timeline_placeholder": "Describe how the symptoms evolved over time.",
      "hpi_advanced_details": "Advanced HPI Details",
      "hpi_disturbances": "Disturbances in sleep, appetite, energy, etc.",
      "hpi_disturbances_placeholder": "e.g., insomnia, fatigue, weight change",
      "hpi_suicidal_ideation": "Suicidal Thoughts or Behaviors",
      "yes_no_explanation": "Yes/No with brief explanation",
      "hpi_negative_history": "Relevant Negative History",
      "hpi_negative_history_placeholder": "Mention conditions that are not present",
      "history_present_illness": "History of Present Illness",
      "hpi_general_info": "General Information",
      "hpi_onset_abrupt": "Abrupt",
      "hpi_onset_acute": "Acute",
      "hpi_onset_subacute": "Subacute",
      "hpi_onset_insidious": "Insidious",
      "hpi_symptom_timeline": "Symptom Timeline",
      "add_another_complaint": "Add Another Complaint",
      "treatment_history": "Treatment History",
      "treatment_past": "Past Treatments",
      "treatment_current": "Current Treatments",
      "past_history": "Past History",
      "past_medical": "Past Medical History",
      "past_psych": "Past Psychiatric History",
      "family_history": "Family History",
      "family_illness": "Family Illnesses",
      "family_social": "Family Social Background",
      "personal_history": "Personal History",
      "personal_perinatal": "Perinatal History",
      "personal_childhood": "Childhood History",
      "personal_education": "Educational History",
      "personal_play": "Play and Social History",
      "personal_adolescence": "Adolescence History",
      "personal_puberty": "Puberty and Sexual History",
      "personal_obstetric": "Obstetric History",
      "personal_occupational": "Occupational History",
      "personal_marital": "Marital and Relationship History",
      "personal_premorbid": "Premorbid Personality",
      "patient_register_success": "Client registered successfully.",
      "patient_register_failed": "Failed to register client. Please try again."
    },
    "register": {
      "welcome": "Welcome to the Coach App",
      "register_therapist": "Register as a New Coach",
      "email": "Email",
      "password": "Password",
      "register": "Register",
      "go_login": "Go to Login instead",
      "success": "Successfully registered"
    },
    "login": {
      "welcome": "Welcome to the Coach App",
      "login_therapist": "Log in as a Coach",
      "email": "Email",
      "password": "Password",
      "login": "Login",
      "go_registration": "Go to Registration instead",
      "success": "Successful login"
    },
    "meetings": {
      "meetings": "Meetings",
      "meeting_start": "Meeting Start",
      "meeting_end": "Meeting End",
      "meeting_location": "Meeting Location",
      "no_meetings_yet": "You don't have any client meetings scheduled yet.",
      "duration": "Duration",
      "duration_in_minutes": "Duration in Minutes",
      "minutes": "minutes",
      "location": "Location",
      "create_meeting": "Create Meeting",
      "create_new_note": "Create New Note",
      "transcribe_meeting": "Transcribe Meeting",
      "meeting_transcription": "Meeting Transcription",
      "new_note": "New Note",
      "title": "Title",
      "language": "Language",
      "content": "Content (Type or Speak)",
      "speak_or_type_here": "Speak or type here...",
      "start_listening": "Start Listening",
      "listening": "Listening...",
      "listening_speak_into_microphone": "Listening... Speak into your microphone.",
      "stop_listening": "Stop Listening",
      "no_notes_yet": "You don't have any notes yet.",
      "delete_meeting": "Delete Meeting",
      "browser_compatibility": "Browser Compatibility",
      "web_search_api_not_supported": "Web Speech API is not supported in your browser. Please try Chrome or Edge for the best experience.",
      "is_past": "Is in the past",
      "error": {
        "error": "Error",
        "no_speech_detected": "No speech detected. Please try speaking a bit louder or clearer.",
        "microphone_not_available": "Microphone not available or permission denied. Please check your microphone settings and browser permissions.",
        "not_allowed": "Permission to use the microphone was denied or has not been granted. Please allow microphone access in your browser settings."
      },
      "save": "Save",
      "cancel": "Cancel",
      "CONFIRMED": "Confirmed",
      "CANCELLED": "Cancelled",
      "PENDING": "Pending",
      "editMeeting": "Edit Meeting",
      "meetingStatus": "Meeting Status",
      "yourNotes": "Your Notes",
      "meeting_created_successfully": "Successfully created meeting",
      "meeting_deleted_successfully": "Successfully deleted meeting",
      "meeting_updated_successfully": "Successfully updated meeting",
      "note_created_successfully": "Successfully created meeting note",
      "note_updated_successfully": "Successfully updated meeting note",
      "note_deleted_successfully": "Successfully deleted meeting note",
      "notes_summary": "Meeting Notes Summary"
    },
    "gad7test": {
      "title": "GAD-7 Assessment",
      "gad7tests": "GAD-7 Tests",
      "completed_gad7tests": "Completed GAD-7 Tests",
      "manage_description": "Set how often the patient should complete the GAD-7 test (in days):",
      "start_date": "Start Date",
      "doEveryNDays": "Every ... days",
      "schedule_summary": "With these settings, the patient will fill out the GAD7 test every {{days}} days starting from {{date}}.",
      "date": "Date",
      "description": "Over the last 2 weeks, how often have you been bothered by the following problems?",
      "question1": "Feeling nervous, anxious or on edge.",
      "question2": "Not being able to stop or control worrying.",
      "question3": "Worrying too much about different things.",
      "question4": "Trouble relaxing.",
      "question5": "Being so restless that it is hard to sit still.",
      "question6": "Becoming easily annoyed or irritable.",
      "question7": "Feeling afraid as if something awful might happen.",
      "total_score": "Total Score",
      "cancel": "Cancel",
      "save_changes": "Save Changes",
      "no_tests_yet": "Client has not filled out any GAD-7 tests yet.",
      "answers": {
        "not_at_all": "Not at all",
        "several_days": "Several days",
        "more_than_half_the_days": "More than half the days",
        "nearly_everyday": "Nearly every day"
      }
    },
    "pages": {
      "home": "Home",
      "login": "Login",
      "logout": "Logout",
      "registration": "Registration",
      "settings": "Settings",
      "patients": {
        "create": "Register New Client",
        "details": "Client Details",
        "conversations": "Conversation Summary",
        "interactions": "Client Interactions",
        "details_update": "Updating Client"
      },
      "chatbot": {
        "create": "Create New Chatbot",
        "details": "Chatbot Details"
      },
      "meetings": {
        "create": "Create New Meeting",
        "details": "Meeting Details"
      },
      "gad7": {
        "manage": "Manage GAD-7 Tests"
      },
      "exercises": {
        "create": "Create Exercise",
        "details": "Exercise Details"
      },
      "chatbot_templates": {
        "create": "Create New Chatbot Template",
        "details": "Chatbot Template Details"
      },
      "counseling_plan": {
        "details": "Counseling Plan"
      },
      "not_found": "Not Found",
      "therapist_chatbot": "Coach Chatbot"
    },
    "files": {
      "download_success": "Successfully downloaded file"
    }
  },
  "ua": {
    "yes": "Так",
    "no": "Ні",
    "header": {
      "title": "Це заголовок",
      "subtitle": "Це поточні сторінки:",
      "dashboard": "Сторінка панелі керування",
      "register": "Сторінка реєстрації",
      "login": "Сторінка входу",
      "patients": "Сторінка огляду клієнтів",
      "patient_detail": "Приклад сторінки деталей клієнта для ID: \"{{id}}\"",
      "patient_create_bot": "Приклад сторінки створення бота для клієнта",
      "bot_edit": "Приклад сторінки редагування бота для ID бота: \"{{id}}\"",
      "create_bot_template": "Сторінка створення шаблону чат-бота",
      "edit_bot_template": "Сторінка редагування шаблону чат-бота для ID: \"{{id}}\"",
      "settings": "Сторінка налаштувань"
    },
    "footer": {
      "title": "Це нижній колонтитул",
      "note": "Запитайте свого особистого помічника..."
    },
    "settings": {
      "title": "Налаштування",
      "language": "Мова",
      "changePasswordTitle": "Змінити пароль",
      "newPassword": "Новий пароль",
      "confirmNewPassword": "Підтвердіть новий пароль",
      "changePasswordButton": "Змінити пароль",
      "LOCAL_UZH": "UZH LLM (Приватний сервер)",
      "AZURE_OPENAI": "OpenAI LLM (Хмара Azure)",
      "llmModel": "Модель LLM",
      "password_changed_success": "Пароль успішно змінено",
      "description": {
        "LOCAL_UZH": "Модель UZH LLM розміщена на приватному сервері. Історія вашої розмови не зберігається, що забезпечує високий рівень конфіденційності та безпеки даних. Недоліком такої підвищеної конфіденційності є те, що ця модель не така потужна, як хмарна альтернатива. В результаті її відповіді можуть бути менш детальними або точними.",
        "AZURE_OPENAI": "Модель OpenAI LLM розміщена на хмарній інфраструктурі Microsoft Azure, сервери якої знаходяться у Швеції. Хоча ця система є безпечною, рівень конфіденційності даних відрізняється від самостійно розміщеної моделі UZH. Основною перевагою цієї моделі є її вища продуктивність, що зазвичай призводить до більш вичерпних і точних відповідей."
      }
    },
    "layout": {
      "dashboard": "Панель керування",
      "dashboards": "Панелі керування",
      "general": "Загальне",
      "settings": "Налаштування",
      "patients": "Клієнти",
      "list_patients": "Список клієнтів",
      "create_patient": "Створити клієнта",
      "patient_details": "Деталі клієнта",
      "logout": "Вийти",
      "overview": "Огляд",
      "account": "Акаунт",
      "send": "Надіслати",
      "expand_AI_assistant": "Розгорнути AI асистента",
      "close": "Закрити"
    },
    "dashboard": {
      "home": "Головна",
      "patient_register_success": "Клієнта успішно зареєстровано.",
      "register_new_patient": "Зареєструвати нового клієнта",
      "add_patient": "Додати клієнта",
      "patients": "Клієнти",
      "patient_id": "ID клієнта",
      "unnamed_patient": "Клієнт без назви",
      "no_patients_found": "Клієнтів не знайдено",
      "new_patient": "Новий клієнт",
      "enter_information_register_new_patient": "Введіть інформацію для реєстрації нового клієнта.",
      "patient_name": "Ім'я клієнта",
      "patient_gender": "Стать",
      "male": "Чоловіча",
      "female": "Жіноча",
      "other": "Інша",
      "patient_age": "Вік",
      "patient_phone_number": "Номер телефону",
      "patient_email": "Електронна пошта",
      "patient_address": "Адреса",
      "patient_description": "Опис клієнта",
      "cancel": "Скасувати",
      "register": "Зареєструвати",
      "rename": "Перейменувати",
      "clone": "Клонувати",
      "delete": "Видалити",
      "save": "Зберегти",
      "welcome_message": "Ви увійшли як: ",
      "upload_file": "Завантажити файл",
      "chatbot_cloned_success": "Чат-бота успішно клоновано.",
      "chatbot_deleted_success": "Чат-бота успішно видалено.",
      "create_bot": "Створити шаблон чат-бота",
      "your_chatbot_templates": "Ваші шаблони чат-ботів",
      "unnamed_bot": "Бот без назви",
      "no_welcome_message_set": "Привітальне повідомлення не встановлено",
      "no_chatbots_created_yet": "Ще не створено жодного чат-бота.",
      "role": "Роль",
      "your_files": "Ваші файли"
    },
    "chatbot": {
      "chatbots": "Чат-боти",
      "chatbot_created_success": "Чат-бота успішно створено.",
      "chatbot_updated_success": "Чат-бота успішно оновлено.",
      "chatbot_named_success": "Чат-бота успішно перейменовано.",
      "chatbot_cloned_success": "Чат-бота успішно клоновано.",
      "chatbot_deleted_success": "Чат-бота успішно видалено.",
      "create_new_chatbot_template": "Створити новий шаблон чат-бота",
      "create_chatbot_from_template": "Створити чат-бота з шаблону",
      "cannot_delete_last_template": "Останній шаблон не може бути видалено.",
      "create_new_chatbot": "Створити нового чат-бота",
      "new_bot": "Новий бот",
      "no_chatbots_created_yet": "Ви ще не створили жодного чат-бота.",
      "client_chatbot": "Чат-бот клієнта",
      "client_chatbots": "Чат-боти клієнта",
      "conversation_summary": "Підсумок розмови",
      "conversations_from": "Розмови з",
      "conversation_private": "Ця розмова клієнта з чат-ботом є приватною.",
      "no_conversations_exist": "Немає розмов.",
      "loading_conversation_summary": "Завантаження підсумку розмови...",
      "what_would_you_like_to_name_your_bot": "Як би ви хотіли назвати свого бота?",
      "enter_bot_name": "Введіть ім'я бота",
      "rename_bot": "Перейменувати бота",
      "enter_new_name_for_bot": "Введіть нове ім'я для вашого бота.",
      "enter_new_bot_name": "Введіть нове ім'я бота",
      "template_not_leaded_yet": "Шаблон ще не завантажено.",
      "chat_service_unavailable": "Сервіс чату наразі недоступний.",
      "chatbot_configuration": "Конфігурація чат-бота",
      "name": "Ім'я",
      "role": "Роль",
      "faq": "Поширені запитання",
      "supportive": "Підтримуючий",
      "counseling": "Консультування",
      "self_help": "Самодопомога",
      "undefined": "Невизначено",
      "language": "Мова",
      "english": "Англійська",
      "german": "Німецька",
      "french": "Французька",
      "spanish": "Іспанська",
      "chatbot_icon": "Іконка чат-бота",
      "chatbot": "Чат-бот",
      "robot": "Робот",
      "person": "Людина",
      "bulb": "Лампочка",
      "book": "Книга",
      "voice": "Голос",
      "none": "Немає",
      "male_voice": "Чоловічий голос",
      "female_voice": "Жіночий голос",
      "robotic_voice": "Роботизований голос",
      "gender": "Стать",
      "neutral": "Нейтральна",
      "male": "Чоловіча",
      "female": "Жіноча",
      "conversation_tone": "Тон розмови",
      "friendly": "Дружній",
      "formal": "Офіційний",
      "casual": "Невимушений",
      "professional": "Професійний",
      "preconfigured_exercise": "Попередньо налаштована вправа",
      "breathing_exercise": "Дихальна вправа",
      "journaling": "Ведення щоденника",
      "relaxation_technique": "Техніка релаксації",
      "additional_exercise": "Додаткова вправа",
      "meditation_practise": "Практика медитації",
      "cbt_example": "Приклад КПТ",
      "animation": "Анімація",
      "simple": "Простий",
      "advanced": "Розширений",
      "welcome_message": "Привітальне повідомлення",
      "chatbot_input_placeholder": "Заповнювач для введення в чат-боті",
      "simulation": "Симуляція",
      "you": "Ви",
      "type_your_message": "Введіть повідомлення...",
      "analytics": "Аналітика",
      "total_chats": "Загальна кількість чатів (Потоків)",
      "thread_id": "ID потоку",
      "no_threads_found": "Потоків не знайдено.",
      "template_files": "Файли шаблонів",
      "active_visiable_to_client": "Активний (видимий для клієнта)",
      "save": "Зберегти",
      "send": "Надіслати",
      "configuration": "Конфігурація",
      "sources": "Джерела",
      "active": "Активний",
      "inactive": "Неактивний"
    },
    "counseling_plan": {
      "counseling_plan": "План консультування",
      "add_existing_exercise": "Додати існуючу вправу",
      "create_new_exercise": "Створити нову вправу",
      "exercise": "Вправа",
      "title": "Назва",
      "exercises": "Вправи",
      "cancel": "Скасувати",
      "start_date": "Дата початку",
      "end_date": "Дата завершення",
      "duration": "Тривалість",
      "weeks": "Тижні",
      "goals": "Цілі",
      "add_a_phase": "Додати фазу",
      "phase_name": "Назва фази",
      "duration_in_weeks": "Тривалість у тижнях",
      "create_phase": "Створити фазу",
      "make_ai_generated_suggestion": "Зробити пропозицію, згенеровану ШІ",
      "exercise_title": "Назва вправи",
      "exerciseDescription": "Опис",
      "exerciseExplanation": "Пояснення (для контексту ШІ)",
      "doEveryNDays": "Повторювати кожні ... дні",
      "exercise_start": "Початок вправи",
      "add_a_goal": "Додати ціль",
      "goal_name": "Назва цілі",
      "goal_description": "Опис цілі",
      "make_ai_generated_suggestion_for_goal": "Зробити пропозицію від ШІ для цілі",
      "make_ai_generated_suggestion_for_phase": "Зробити пропозицію від ШІ для фази",
      "make_ai_generated_suggestion_for_exercise": "Зробити пропозицію від ШІ для вправи",
      "create_goal": "Створити ціль",
      "counseling_start_date": "Дата початку консультування",
      "counseling_plan_phases": "Фази плану консультування",
      "phase_updated_success": "Фазу успішно оновлено",
      "update_phase": "Оновити фазу",
      "phase_goal_updated_success": "Ціль фази успішно оновлено",
      "updateGoal": "Оновити ціль",
      "phase_created_success": "Фазу успішно створено",
      "updated_successfully": "Успішно оновлено",
      "exercise_added_success": "Вправу успішно додано",
      "phase_deleted_success": "Фазу успішно видалено",
      "exercise_created_success": "Вправу успішно створено",
      "goal_created_success": "Ціль успішно створено",
      "amountOfPhases": "Кількість фаз",
      "goalsCompleted": "Цілей досягнуто",
      "goalsCompleted2": "цілей досягнуто",
      "phase": "Фаза",
      "completed": "завершено"
    },
    "exercise": {
      "upload_image": "Завантажити зображення",
      "description": "Опис",
      "add_input_field": "Додати поле для введення",
      "description_of_input": "Опис поля для введення",
      "add_text": "Додати текст",
      "text": "Текст",
      "create_new_exercise": "Створити нову вправу",
      "exercise": "Вправа",
      "exercises": "Вправи",
      "exercise_start": "Початок вправи",
      "duration_in_weeks": "Тривалість у тижнях",
      "exercise_end": "Кінець вправи",
      "is_paused": "Призупинено",
      "is_active": "Активно",
      "is_currently_paused": "Наразі призупинено",
      "is_exercise_paused": "Вправу призупинено",
      "no_exercises_yet": "Ви ще не додали жодної вправи.",
      "no_exercise_components_yet": "Ви ще не додали жодних компонентів вправи.",
      "image": "Зображення",
      "file": "Файл",
      "doEveryNDays": "Повторювати кожні ... дні",
      "privateInput": "Приватне поле для введення",
      "sharedInput": "Спільне поле для введення",
      "addPrivateInput": "Додати приватне поле для введення",
      "addSharedInput": "Додати спільне поле для введення",
      "order": "Порядок",
      "desciption_of_input": "Опис поля для введення",
      "title": "Назва",
      "exerciseDescription": "Опис",
      "exerciseExplanation": "Пояснення (для контексту ШІ)",
      "submit": "Надіслати",
      "cancel": "Скасувати",
      "edit_exercise": "Редагувати вправу",
      "exercise_components": "Компоненти вправи",
      "delete_exercise": "Видалити вправу",
      "addYoutubeVideo": "Додати відео з YouTube",
      "youtubeVideoUrl": "URL-адреса відео з YouTube",
      "youtubeVideo": "Відео з YouTube",
      "noUrlProvided": "URL-адресу YouTube не надано",
      "invalidUrlProvided": "Недійсна URL-адреса YouTube",
      "feedback": "Відгук",
      "startTime": "Час початку",
      "endTime": "Час завершення",
      "moodsBefore": "Настрій до",
      "moodsAfter": "Настрій після",
      "editMode": "Режим редагування",
      "viewMode": "Режим перегляду",
      "youtubeDescription": "Опис відео",
      "exercise_created_successfully": "Вправу успішно створено",
      "exercise_updated_successfully": "Вправу успішно оновлено",
      "exercise_deleted_successfully": "Вправу успішно видалено",
      "component_created_successfully": "Компонент вправи успішно створено",
      "component_updated_successfully": "Компонент вправи успішно оновлено",
      "component_deleted_successfully": "Компонент вправи успішно видалено",
      "exercise_removed_successfully": "Вправу успішно видалено",
      "goal_removed_successfully": "Ціль успішно видалено",
      "client_feedback": "Відгук клієнта",
      "no_client_feedback": "Клієнт ще не надав відгук щодо цієї вправи.",
      "privateInputTooltip": "Це приватне поле для введення дозволяє клієнту записувати власні думки, які не будуть передані коучу.",
      "sharedInputTooltip": "Це спільне поле для введення дозволяє клієнту записувати власні думки, які будуть видимі для коуча.",
      "completions": "Виконані вправи",
      "moodtracking": {
        "very_unpleasant": "дуже неприємно",
        "unpleasant": "неприємний",
        "neutral": "нейтральний",
        "pleasant": "приємний",
        "very_pleasant": "дуже приємно"
      }
    },
    "not_found": {
      "title": "404 - Сторінку не знайдено",
      "message": "Ой! Сторінки, яку ви шукаєте, не існує."
    },
    "patient_detail": {
      "message": "Це сторінка деталей клієнта з ID",
      "view_client_interactions": "Переглянути взаємодії з клієнтом",
      "client": "Клієнт",
      "email_client_app": "Email (для входу в додаток клієнта)",
      "initial_password_client_app": "Початковий пароль (для входу в додаток клієнта)",
      "client_app_link": "Посилання на додаток клієнта",
      "age": "Вік",
      "gender": "Стать",
      "phone": "Телефон",
      "address": "Адреса",
      "date_of_admission": "Дата прийому",
      "view_more_details": "Переглянути більше деталей",
      "loading_patient_data": "Завантаження даних клієнта...",
      "counseling_plan": "План консультування",
      "go_to_counseling_plan": "Перейти до плану консультування",
      "current_phase": "Поточна фаза",
      "currently_no_phase_is_active": "Наразі жодна фаза не активна.",
      "create_a_new_chatbot": "Створити нового чат-бота",
      "please_enter_name_for_chatbot": "Будь ласка, введіть ім'я для вашого нового чат-бота",
      "chatbot_name": "Ім'я чат-бота",
      "create_bot": "Створити бота",
      "files_visible_to_client": "Файли, видимі для клієнта",
      "files_visible_only_to_coach": "Файли, видимі лише для коуча",
      "no_files_uploaded_yet": "Ви ще не завантажили жодних файлів.",
      "file_name": "Назва файлу",
      "actions": "Дії",
      "download": "Завантажити",
      "delete": "Видалити",
      "edit": "Редагувати",
      "save_changes": "Зберегти зміни",
      "file_upload_success": "Файл успішно завантажено",
      "file_delete_success": "Файл успішно видалено",
      "manage_tests": "Керувати GAD7 тестами"
    },
    "patient_interactions": {
      "interaction_type": "Тип взаємодії",
      "start_date": "Дата початку",
      "end_date": "Дата завершення",
      "time": "Час",
      "date": "Дата",
      "last_week": "Останній тиждень",
      "last_two_weeks": "Останні 2 тижні",
      "last_three_weeks": "Останні 3 тижні",
      "loading": "Завантаження даних про взаємодії з клієнтом...",
      "fetch_error": "Помилка отримання даних про взаємодії з клієнтом.",
      "no_data": "Немає доступних даних журналу клієнта.",
      "interactions": "Взаємодії",
      "export_to_csv": "Експортувати в CSV",
      "log_types": {
        "journal_creation": "Створення щоденника",
        "journal_update": "Оновлення щоденника",
        "exercise_start": "Початок вправи",
        "exercise_completion": "Завершення вправи",
        "exercise_update": "Оновлення вправи",
        "general_conversation_creation": "Створення загальної розмови",
        "general_conversation_name_update": "Оновлення назви загальної розмови",
        "general_conversation_message_creation": "Створення повідомлення в загальній розмові",
        "document_conversation_message_creation": "Створення повідомлення в розмові по документу",
        "exercise_conversation_message_creation": "Створення повідомлення в розмові по вправі",
        "journal_conversation_message_creation": "Створення повідомлення в розмові по щоденнику",
        "chatbot_icon_update": "Оновлення іконки чат-бота",
        "harmful_content_detected": "Виявлено шкідливий вміст",
        "document_read": "Документ прочитано",
        "psychological_test_completed": "Психологічний тест завершено"
      }
    },
    "patient_create": {
      "title": "Це сторінка для створення нового клієнта",
      "new_patient": "Новий клієнт",
      "create_patient": "Створити клієнта",
      "patient_name": "Ім'я клієнта",
      "patient_age": "Вік",
      "patient_gender": "Стать",
      "male": "Чоловіча",
      "female": "Жіноча",
      "other": "Інша",
      "patient_marital_status": "Сімейний стан",
      "patient_religion": "Релігія",
      "patient_education": "Освіта",
      "patient_occupation": "Професія",
      "patient_income": "Дохід",
      "patient_address": "Адреса",
      "patient_phone": "Номер телефону",
      "patient_email": "Електронна пошта",
      "patient_date_of_admission": "Дата прийому",
      "register": "Зареєструвати",
      "cancel": "Скасувати",
      "complaint": "Скарга",
      "main_complaints": "Основні скарги",
      "history_of_present_illness": "Анамнез теперішнього захворювання",
      "hpi_duration": "Тривалість",
      "hpi_onset": "Початок",
      "onset_abrupt": "Раптовий",
      "onset_acute": "Гострий",
      "onset_subacute": "Підгострий",
      "onset_insidious": "Поступовий",
      "hpi_course": "Перебіг",
      "hpi_course_continuous": "Безперервний",
      "hpi_course_episodic": "Епізодичний",
      "hpi_course_fluctuating": "Хвилеподібний",
      "hpi_course_deteriorating": "Погіршується",
      "hpi_course_improving": "Покращується",
      "hpi_course_unclear": "Незрозумілий",
      "hpi_precipitating_factors": "Провокуючі фактори",
      "hpi_aggravating_relieving": "Фактори, що погіршують та полегшують стан",
      "hpi_aggravating_relieving_placeholder": "Що робить стан кращим або гіршим?",
      "hpi_timeline": "Хронологія",
      "hpi_timeline_placeholder": "Опишіть, як симптоми розвивалися з часом.",
      "hpi_advanced_details": "Розширені деталі анамнезу",
      "hpi_disturbances": "Порушення сну, апетиту, енергії тощо.",
      "hpi_disturbances_placeholder": "напр., безсоння, втома, зміна ваги",
      "hpi_suicidal_ideation": "Суїцидальні думки або поведінка",
      "yes_no_explanation": "Так/Ні з коротким поясненням",
      "hpi_negative_history": "Релевантний негативний анамнез",
      "hpi_negative_history_placeholder": "Згадайте стани, які відсутні",
      "history_present_illness": "Анамнез теперішнього захворювання",
      "hpi_general_info": "Загальна інформація",
      "hpi_onset_abrupt": "Раптовий",
      "hpi_onset_acute": "Гострий",
      "hpi_onset_subacute": "Підгострий",
      "hpi_onset_insidious": "Поступовий",
      "hpi_symptom_timeline": "Хронологія симптомів",
      "add_another_complaint": "Додати іншу скаргу",
      "treatment_history": "Історія лікування",
      "treatment_past": "Минулі лікування",
      "treatment_current": "Поточні лікування",
      "past_history": "Минулий анамнез",
      "past_medical": "Минулий медичний анамнез",
      "past_psych": "Минулий психіатричний анамнез",
      "family_history": "Сімейний анамнез",
      "family_illness": "Сімейні захворювання",
      "family_social": "Соціальне походження сім'ї",
      "personal_history": "Особистий анамнез",
      "personal_perinatal": "Перинатальний анамнез",
      "personal_childhood": "Дитячий анамнез",
      "personal_education": "Освітній анамнез",
      "personal_play": "Ігровий та соціальний анамнез",
      "personal_adolescence": "Підлітковий анамнез",
      "personal_puberty": "Пубертатний та сексуальний анамнез",
      "personal_obstetric": "Акушерський анамнез",
      "personal_occupational": "Професійний анамнез",
      "personal_marital": "Подружній та стосунковий анамнез",
      "personal_premorbid": "Преморбідна особистість",
      "patient_register_success": "Клієнта успішно зареєстровано.",
      "patient_register_failed": "Не вдалося зареєструвати клієнта. Будь ласка, спробуйте ще раз."
    },
    "register": {
      "welcome": "Ласкаво просимо до додатку для коучів",
      "register_therapist": "Зареєструватися як новий коуч",
      "email": "Електронна пошта",
      "password": "Пароль",
      "register": "Зареєструватися",
      "go_login": "Перейти до входу",
      "success": "Успішно зареєстровано"
    },
    "login": {
      "welcome": "Ласкаво просимо до додатку для коучів",
      "login_therapist": "Увійти як коуч",
      "email": "Електронна пошта",
      "password": "Пароль",
      "login": "Увійти",
      "go_registration": "Перейти до реєстрації",
      "success": "Вхід виконано успішно"
    },
    "meetings": {
      "meetings": "Зустрічі",
      "meeting_start": "Початок зустрічі",
      "meeting_end": "Кінець зустрічі",
      "meeting_location": "Місце зустрічі",
      "no_meetings_yet": "У вас ще немає запланованих зустрічей з клієнтами.",
      "duration": "Тривалість",
      "duration_in_minutes": "Тривалість у хвилинах",
      "minutes": "хвилини",
      "location": "Місцезнаходження",
      "create_meeting": "Створити зустріч",
      "create_new_note": "Створити нову нотатку",
      "transcribe_meeting": "Транскрибувати зустріч",
      "meeting_transcription": "Транскрипція зустрічі",
      "new_note": "Нова нотатка",
      "title": "Назва",
      "language": "Мова",
      "content": "Вміст (Введіть або промовте)",
      "speak_or_type_here": "Говоріть або друкуйте тут...",
      "start_listening": "Почати слухати",
      "listening": "Слухаю...",
      "listening_speak_into_microphone": "Слухаю... Говоріть у мікрофон.",
      "stop_listening": "Зупинити слухання",
      "no_notes_yet": "У вас ще немає нотаток.",
      "delete_meeting": "Видалити зустріч",
      "browser_compatibility": "Сумісність з браузером",
      "web_search_api_not_supported": "Web Speech API не підтримується у вашому браузері. Будь ласка, спробуйте Chrome або Edge для кращої роботи.",
      "is_past": "Минула",
      "error": {
        "error": "Помилка",
        "no_speech_detected": "Мовлення не розпізнано. Спробуйте говорити голосніше або чіткіше.",
        "microphone_not_available": "Мікрофон недоступний або дозвіл відхилено. Перевірте налаштування мікрофона та дозволи браузера.",
        "not_allowed": "Дозвіл на використання мікрофона було відхилено або не надано. Дозвольте доступ до мікрофона в налаштуваннях вашого браузера."
      },
      "save": "Зберегти",
      "cancel": "Скасувати",
      "CONFIRMED": "Підтверджено",
      "CANCELLED": "Скасовано",
      "PENDING": "Очікує",
      "editMeeting": "Редагувати зустріч",
      "meetingStatus": "Статус зустрічі",
      "yourNotes": "Ваші нотатки",
      "meeting_created_successfully": "Зустріч успішно створено",
      "meeting_deleted_successfully": "Зустріч успішно видалено",
      "meeting_updated_successfully": "Зустріч успішно оновлено",
      "note_created_successfully": "Нотатку до зустрічі успішно створено",
      "note_updated_successfully": "Нотатку до зустрічі успішно оновлено",
      "note_deleted_successfully": "Нотатку до зустрічі успішно видалено",
      "notes_summary": "Підсумок нотаток"
    },
    "gad7test": {
      "title": "Оцінка за шкалою GAD-7",
      "gad7tests": "Тести GAD-7",
      "completed_gad7tests": "Завершені тести GAD-7",
      "manage_description": "Вкажіть, як часто клієнт повинен проходити тест GAD-7 (у днях):",
      "start_date": "Дата початку",
      "doEveryNDays": "Кожні ... днів",
      "schedule_summary": "За цих налаштувань пацієнт заповнюватиме тест GAD7 кожні {{days}} днів, починаючи з {{date}}.",
      "date": "Дата",
      "description": "Протягом останніх 2 тижнів, як часто вас турбували наступні проблеми?",
      "question1": "Відчуття нервозності, тривоги або напруженості.",
      "question2": "Неможливість припинити або контролювати занепокоєння.",
      "question3": "Надмірне занепокоєння з приводу різних речей.",
      "question4": "Труднощі з розслабленням.",
      "question5": "Така неспокійність, що важко всидіти на місці.",
      "question6": "Легка дратівливість або роздратованість.",
      "question7": "Відчуття страху, ніби може статися щось жахливе.",
      "total_score": "Загальний бал",
      "cancel": "Скасувати",
      "save_changes": "Зберегти зміни",
      "no_tests_yet": "Клієнт ще не заповнював жодних тестів GAD-7.",
      "answers": {
        "not_at_all": "Зовсім ні",
        "several_days": "Кілька днів",
        "more_than_half_the_days": "Більше половини днів",
        "nearly_everyday": "Майже щодня"
      }
    },
    "pages": {
      "home": "Головна",
      "login": "Вхід",
      "logout": "Вихід",
      "registration": "Реєстрація",
      "settings": "Налаштування",
      "patients": {
        "create": "Зареєструвати нового клієнта",
        "details": "Деталі клієнта",
        "conversations": "Підсумок розмов",
        "interactions": "Взаємодії з клієнтом",
        "details_update": "Оновлення клієнта"
      },
      "chatbot": {
        "create": "Створити нового чат-бота",
        "details": "Деталі чат-бота"
      },
      "meetings": {
        "create": "Створити нову зустріч",
        "details": "Деталі зустрічі"
      },
      "gad7": {
        "manage": "Керувати тестами GAD-7"
      },
      "exercises": {
        "create": "Створити вправу",
        "details": "Деталі вправи"
      },
      "chatbot_templates": {
        "create": "Створити новий шаблон чат-бота",
        "details": "Деталі шаблону чат-бота"
      },
      "counseling_plan": {
        "details": "План консультування"
      },
      "not_found": "Не знайдено",
      "therapist_chatbot": "Чат-бот коуча"
    },
    "files": {
      "download_success": "Файл успішно завантажено"
    }
  }
}

export default Resources;
