interface Resources {
  "de": {
    "header": {
      "title": "Dies ist der Header",
      "subtitle": "Dies sind die aktuellen Seiten:",
      "dashboard": "Dashboard-Seite",
      "register": "Registrierungsseite",
      "login": "Login-Seite",
      "patients": "Übersichtsseite der Klienten",
      "patient_detail": "Beispielseite Klientendetails für ID: \"{{id}}\"",
      "patient_create_bot": "Beispielseite zur Erstellung eines Klienten-Bots",
      "bot_edit": "Beispiel: Bot bearbeiten für Bot-ID: \"{{id}}\"",
      "create_bot_template": "Seite zum Erstellen einer ChatBot-Vorlage",
      "edit_bot_template": "ChatBot-Vorlage bearbeiten für ID: \"{{id}}\"",
      "settings": "Einstellungen-Seite"
    },
    "footer": {
      "title": "Dies ist der Footer",
      "note": "Frage deinen persönlichen Assistenten..."
    },
    "settings": {
      "title": "Einstellungen",
      "language": "Sprache",
      "changePasswordTitle": "Passwort ändern",
      "newPassword": "Neues Passwort",
      "confirmNewPassword": "Neues Passwort bestätigen",
      "changePasswordButton": "Absenden"
    },
    "layout": {
      "dashboard": "Dashboard",
      "dashboards": "Dashboards",
      "general": "Allgemein",
      "settings": "Einstellungen",
      "patients": "Klienten",
      "list_patients": "Klienten auflisten",
      "create_patient": "Klienten erstellen",
      "patient_details": "Klientendetails",
      "logout": "Abmelden",
      "overview": "Übersicht",
      "account": "Konto"
    },
    "dashboard": {
      "patient_register_success": "Klient erfolgreich registriert.",
      "register_new_patient": "Neuen Klienten registrieren",
      "add_patient": "Klienten hinzufügen",
      "patients": "Klienten",
      "patient_id": "Klienten-ID",
      "no_patients_found": "Keine Klienten gefunden",
      "new_patient": "Neuer Klient",
      "enter_information_register_new_patient": "Gib Informationen ein, um einen neuen Klienten zu registrieren.",
      "patient_name": "Klientenname",
      "patient_gender": "Geschlecht",
      "male": "Männlich",
      "female": "Weiblich",
      "other": "Andere",
      "patient_age": "Alter",
      "patient_phone_number": "Telefonnummer",
      "patient_email": "E-Mail",
      "patient_address": "Adresse",
      "patient_description": "Klientenbeschreibung",
      "cancel": "Abbrechen",
      "register": "Registrieren",
      "rename": "Umbenennen",
      "clone": "Klonen",
      "delete": "Löschen",
      "save": "Speichern",
      "welcome_message": "Du bist eingeloggt als: ",
      "upload_file": "Datei hochladen",
      "chatbot_cloned_success": "Chatbot erfolgreich geklont.",
      "chatbot_deleted_success": "Chatbot erfolgreich gelöscht.",
      "create_bot": "Chatbot-Vorlage erstellen",
      "your_chatbot_templates": "Deine Chatbot-Vorlagen",
      "unnamed_bot": "Unbenannter Bot",
      "no_welcome_message_set": "Keine Willkommensnachricht festgelegt",
      "no_chatbots_created_yet": "Noch keine Chatbots erstellt.",
      "role": "Rolle",
      "your_files": "Deine Dateien"
    },
    "chatbot": {
      "chatbots": "Chatbots",
      "chatbot_created_success": "Chatbot erfolgreich erstellt.",
      "chatbot_updated_success": "Chatbot erfolgreich aktualisiert.",
      "chatbot_named_success": "Chatbot erfolgreich umbenannt.",
      "create_new_chatbot_template": "Neue Chatbot-Vorlage erstellen",
      "create_chatbot_from_template": "Chatbot aus Vorlage erstellen",
      "create_new_chatbot": "Neuen Chatbot erstellen",
      "new_bot": "Neuer Bot",
      "no_chatbots_created_yet": "Noch keine Chatbots erstellt.",
      "client_chatbot": "Klienten-Chatbot",
      "client_chatbots": "Klienten-Chatbots",
      "conversation_summary": "Gesprächszusammenfassung",
      "what_would_you_like_to_name_your_bot": "Wie möchtest du deinen Bot nennen?",
      "enter_bot_name": "Botnamen eingeben",
      "rename_bot": "Bot umbenennen",
      "enter_new_name_for_bot": "Gib den neuen Namen für deinen Bot ein.",
      "enter_new_bot_name": "Neuen Botnamen eingeben",
      "template_not_leaded_yet": "Vorlage noch nicht geladen.",
      "chat_service_unavailable": "Chatdienst ist derzeit nicht verfügbar.",
      "chatbot_configuration": "Chatbot-Konfiguration",
      "name": "Name",
      "role": "Rolle",
      "faq": "FAQ",
      "supportive": "Unterstützend",
      "counseling": "Beratung",
      "self_help": "Selbsthilfe",
      "undefined": "Nicht definiert",
      "language": "Sprache",
      "english": "Englisch",
      "german": "Deutsch",
      "french": "Französisch",
      "spanish": "Spanisch",
      "chatbot_icon": "Chatbot-Symbol",
      "chatbot": "Chatbot",
      "robot": "Roboter",
      "person": "Person",
      "bulb": "Glühbirne",
      "book": "Buch",
      "voice": "Stimme",
      "none": "Keine",
      "male_voice": "Männliche Stimme",
      "female_voice": "Weibliche Stimme",
      "robotic_voice": "Roboterstimme",
      "gender": "Geschlecht",
      "neutral": "Neutral",
      "male": "Männlich",
      "female": "Weiblich",
      "conversation_tone": "Gesprächston",
      "friendly": "Freundlich",
      "formal": "Formell",
      "casual": "Locker",
      "professional": "Professionell",
      "preconfigured_exercise": "Vorkonfigrierte Übung",
      "breathing_exercise": "Atemübung",
      "journaling": "Reflexionsjournal",
      "relaxation_technique": "Entspannungstechnik",
      "additional_exercise": "Zusätzliche Übung",
      "meditation_practise": "Meditationsübung",
      "cbt_example": "CBT-Beispiel",
      "animation": "Animation",
      "simple": "Einfach",
      "advanced": "Fortgeschritten",
      "welcome_message": "Begrüßungsnachricht",
      "chatbot_input_placeholder": "Platzhalter für Chatbot-Eingabe",
      "simulation": "Simulation",
      "you": "Du",
      "type_your_message": "Gib eine Nachricht ein...",
      "analytics": "Analysen",
      "total_chats": "Gesamtanzahl Chats (Threads)",
      "thread_id": "Thread-ID",
      "no_threads_found": "Keine Threads gefunden.",
      "template_files": "Vorlagendateien"
    },
    "counseling_plan": {
      "add_existing_exercise": "Bestehende Übung hinzufügen",
      "create_new_exercise": "Neue Übung erstellen",
      "exercise": "Übung",
      "title": "Titel",
      "exercises": "Übungen",
      "cancel": "Abbrechen",
      "start_date": "Startdatum",
      "end_date": "Enddatum",
      "duration": "Dauer",
      "weeks": "Wochen",
      "goals": "Ziele",
      "add_a_phase": "Phase hinzufügen",
      "phase_name": "Phasenname",
      "duration_in_weeks": "Dauer in Wochen",
      "create_phase": "Phase erstellen",
      "make_ai_generated_suggestion": "KI-generierten Vorschlag erstellen",
      "exercise_title": "Übungstitel",
      "exercise_type": "Übungstyp",
      "exercise_start": "Übungsbeginn",
      "add_a_goal": "Ziel hinzufügen",
      "goal_name": "Zielname",
      "goal_description": "Zielbeschreibung",
      "make_ai_generated_suggestion_for_goal": "KI-generierten Vorschlag für Ziel erstellen",
      "make_ai_generated_suggestion_for_phase": "KI-generierten Vorschlag für Phase erstellen",
      "make_ai_generated_suggestion_for_exercise": "KI-generierten Vorschlag für Übung erstellen",
      "create_goal": "Ziel erstellen",
      "counseling_start_date": "Beginn der Beratung",
      "counseling_plan_phases": "Beratungsplan-Phasen"
    },
    "exercise": {
      "upload_image": "Bild hochladen",
      "description": "Beschreibung",
      "add_input_field": "Eingabefeld hinzufügen",
      "description_of_input": "Eingabebeschreibung",
      "add_text": "Text hinzufügen",
      "text": "Text",
      "create_new_exercise": "Neue Übung erstellen",
      "exercise": "Übung",
      "exercise_type": "Übungstyp",
      "exercise_start": "Übungsbeginn",
      "duration_in_weeks": "Dauer in Wochen",
      "exercise_end": "Übungsende",
      "is_paused": "Pausiert",
      "is_currently_paused": "Derzeit pausiert",
      "is_exercise_paused": "Ist Übung pausiert",
      "no_exercises_yet": "Sie haben noch keine Übungen hinzugefügt...",
      "no_exercise_components_yet": "Sie haben noch keine Übungskomponenten hinzugefügt...",
      "image": "Bild",
      "file": "Datei",
      "input_field": "Eingabefeld",
      "order": "Reihenfolge",
      "desciption_of_input": "Eingabebeschreibung",
      "title": "Titel",
      "submit": "Absenden",
      "cancel": "Abbrechen",
      "edit_exercise": "Übung bearbeiten",
      "exercise_components": "Übungskomponenten",
      "delete_exercise": "Übung löschen"
    },
    "not_found": {
      "title": "404 - Seite nicht gefunden",
      "message": "Ups! Die gesuchte Seite existiert nicht."
    },
    "patient_detail": {
      "message": "Dies ist die Detailseite des Klienten mit der ID",
      "view_client_interactions": "Klienteninteraktionen anzeigen",
      "client": "Klient",
      "email_client_app": "E-Mail (für Login in der Klienten-App)",
      "initial_password_client_app": "Initialpasswort (für Login in der Klienten-App)",
      "client_app_link": "Link zur Klienten-App",
      "age": "Alter",
      "gender": "Geschlecht",
      "phone": "Telefon",
      "address": "Adresse",
      "date_of_admission": "Aufnahmedatum",
      "loading_patient_data": "Lade Klientendaten...",
      "counseling_plan": "Beratungsplan",
      "go_to_counseling_plan": "Zum Beratungsplan",
      "current_phase": "Aktuelle Phase",
      "currently_no_phase_is_active": "Derzeit ist keine Phase aktiv.",
      "create_a_new_chatbot": "Einen neuen Chatbot erstellen",
      "please_enter_name_for_chatbot": "Bitte gib einen Namen für deinen neuen Chatbot ein",
      "chatbot_name": "Chatbot-Name",
      "create_bot": "Bot erstellen",
      "files_visible_to_client": "Für Klienten sichtbare Dateien",
      "files_visible_only_to_coach": "Nur für Coach sichtbare Dateien"
    },
    "patient_interactions": {
      "interaction_type": "Interaktionstyp",
      "start_date": "Startdatum",
      "end_date": "Enddatum",
      "time": "Zeit",
      "date": "Datum"
    },
    "patient_create": {
      "title": "Dies ist die Seite zur Erstellung eines neuen Klienten",
      "new_patient": "Neuer Klient",
      "create_patient": "Klient anlegen",
      "patient_name": "Name",
      "patient_age": "Alter",
      "patient_gender": "Geschlecht",
      "male": "Männlich",
      "female": "Weiblich",
      "other": "Anderes",
      "patient_marital_status": "Familienstand",
      "patient_religion": "Religion",
      "patient_education": "Bildungsstand",
      "patient_occupation": "Beruf",
      "patient_income": "Einkommen",
      "patient_address": "Adresse",
      "patient_phone": "Telefonnummer",
      "patient_email": "E-Mail",
      "patient_date_of_admission": "Aufnahmedatum",
      "register": "Registrieren",
      "cancel": "Abbrechen",
      "complaint": "Beschwerde",
      "main_complaints": "Hauptbeschwerden",
      "history_of_present_illness": "Anamnese der aktuellen Erkrankung",
      "hpi_duration": "Dauer",
      "hpi_onset": "Beginn",
      "onset_abrupt": "Plötzlich",
      "onset_acute": "Akut",
      "onset_subacute": "Subakut",
      "onset_insidious": "Schleichend",
      "hpi_course": "Verlauf",
      "hpi_course_continuous": "Kontinuierlich",
      "hpi_course_episodic": "Episodisch",
      "hpi_course_fluctuating": "Schwankend",
      "hpi_course_deteriorating": "Verschlechternd",
      "hpi_course_improving": "Bessernd",
      "hpi_course_unclear": "Unklar",
      "hpi_precipitating_factors": "Auslösende Faktoren",
      "hpi_aggravating_relieving": "Verstärkende und lindernde Faktoren",
      "hpi_aggravating_relieving_placeholder": "Was verschlimmert oder verbessert die Beschwerden?",
      "hpi_timeline": "Zeitlicher Verlauf",
      "hpi_timeline_placeholder": "Beschreiben Sie, wie sich die Symptome im Laufe der Zeit entwickelt haben.",
      "hpi_advanced_details": "Detaillierte Anamnese",
      "hpi_disturbances": "Störungen (Schlaf, Appetit, Energie etc.)",
      "hpi_disturbances_placeholder": "z.B. Schlaflosigkeit, Müdigkeit, Gewichtsveränderung",
      "hpi_suicidal_ideation": "Suizidgedanken oder -verhalten",
      "yes_no_explanation": "Ja/Nein mit kurzer Erläuterung",
      "hpi_negative_history": "Relevante Negativ-Anamnese",
      "hpi_negative_history_placeholder": "Erwähnen Sie nicht vorhandene Erkrankungen",
      "history_present_illness": "Anamnese der aktuellen Erkrankung",
      "hpi_general_info": "Allgemeine Informationen",
      "hpi_onset_abrupt": "Plötzlich",
      "hpi_onset_acute": "Akut",
      "hpi_onset_subacute": "Subakut",
      "hpi_onset_insidious": "Schleichend",
      "hpi_symptom_timeline": "Symptomverlauf",
      "add_another_complaint": "Weitere Beschwerde hinzufügen",
      "treatment_history": "Behandlungsgeschichte",
      "treatment_past": "Frühere Behandlungen",
      "treatment_current": "Aktuelle Behandlungen",
      "past_history": "Vorgeschichte",
      "past_medical": "Medizinische Vorgeschichte",
      "past_psych": "Psychiatrische Vorgeschichte",
      "family_history": "Familienanamnese",
      "family_illness": "Erkrankungen in der Familie",
      "family_social": "Sozialer Familienhintergrund",
      "personal_history": "Persönliche Anamnese",
      "personal_perinatal": "Perinatale Anamnese",
      "personal_childhood": "Kindheitsgeschichte",
      "personal_education": "Bildungsweg",
      "personal_play": "Spiel- und Sozialverhalten",
      "personal_adolescence": "Jugendgeschichte",
      "personal_puberty": "Pubertät und Sexualanamnese",
      "personal_obstetric": "Geburtsanamnese",
      "personal_occupational": "Berufliche Anamnese",
      "personal_marital": "Partnerschafts- und Beziehungsanamnese",
      "personal_premorbid": "Prämorbide Persönlichkeit",
      "patient_register_success": "Klient erfolgreich registriert.",
      "patient_register_failed": "Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut."
    },
    "register": {
      "welcome": "Willkommen bei der Therapeut:innen-App",
      "register_therapist": "Als neue:r Therapeut:in registrieren",
      "email": "E-Mail",
      "password": "Passwort",
      "register": "Registrieren",
      "go_login": "Stattdessen zum Login"
    },
    "login": {
      "welcome": "Willkommen bei der Therapeut:innen-App",
      "login_therapist": "Als Therapeut:in einloggen",
      "email": "E-Mail",
      "password": "Passwort",
      "login": "Einloggen",
      "go_registration": "Stattdessen zur Registrierung"
    },
    "meetings": {
      "meetings": "Meetings",
      "meeting_start": "Meeting-Start",
      "meeting_end": "Meeting-Ende",
      "meeting_location": "Meeting-Ort",
      "duration": "Dauer",
      "duration_in_minutes": "Dauer in Minuten",
      "minutes": "Minuten",
      "location": "Ort",
      "create_meeting": "Meeting erstellen",
      "create_new_note": "Neue Notiz erstellen",
      "transcribe_meeting": "Meeting transkribieren",
      "meeting_transcription": "Meeting-Transkription",
      "new_note": "Neue Notiz",
      "title": "Titel",
      "language": "Sprache",
      "content": "Inhalt (Tippen oder Sprechen)",
      "speak_or_type_here": "Tippe oder sprich hier...",
      "start_listening": "Zuhören starten",
      "listening": "Zuhöre...",
      "listening_speak_into_microphone": "Zuhöre... Bitte sprich in dein Mikrofon.",
      "stop_listening": "Zuhören stoppen",
      "no_notes_yet": "Du hast noch keine Notizen.",
      "delete_meeting": "Meeting löschen",
      "browser_compatibility": "Browser-Kompatibilität",
      "web_search_api_not_supported": "Web Speech API wird in deinem Browser nicht unterstützt. Bitte nutze Chrome oder Edge für das beste Erlebnis.",
      "error": {
        "error": "Fehler",
        "no_speech_detected": "Keine Sprache erkannt. Bitte sprich etwas deutlicher.",
        "microphone_not_available": "Mikrofon nicht verfügbar oder Erlaubnis verweigert. Bitte überprüfe deine Mikrofoneinstellungen.",
        "not_allowed": "Erlaubnis zur Mikrofonbenutzung wurde verweigert oder nicht erteilt. Bitte erlaube den Zugriff in den Browser-Einstellungen."
      },
      "save": "Speichern",
      "cancel": "Abbrechen",
      "CONFIRMED": "Bestätigt",
      "CANCELLED": "Abgebrochen",
      "PENDING": "Ausstehend",
      "editMeeting": "Meeting bearbeiten",
      "meetingStatus": "Meeting-Status",
      "yourNotes": "Deine Notizen"
    },
    "gad7test": {
      "title": "GAD-7 Assessment",
      "gad7tests": "GAD-7 Tests",
      "create_gad7test": "GAD-7 Test erstellen",
      "description": "In den letzten 2 Wochen, wie oft wurdest du durch folgende Probleme beeinträchtigt?",
      "question1": "Dich nervös, ängstlich oder gereizt gefühlt.",
      "question2": "Nicht aufhören oder aufhören können zu sorgen.",
      "question3": "Zu viel Sorge um verschiedene Dinge.",
      "question4": "Schwierigkeiten beim Entspannen.",
      "question5": "So unruhig gewesen, dass es schwer war, still zu sitzen.",
      "question6": "Leicht gereizt oder ärgerlich geworden.",
      "question7": "Angst gehabt, als ob etwas Schreckliches passieren könnte.",
      "total_score": "Gesamtpunktzahl",
      "cancel": "Abbrechen",
      "submit": "Absenden",
      "no_tests_yet": "Du hast noch keinen GAD-7 Test erstellt.",
      "answers": {
        "not_at_all": "Überhaupt nicht",
        "several_days": "An einigen Tagen",
        "more_than_half_the_days": "An mehr als der Hälfte der Tage",
        "nearly_everyday": "Fast jeden Tag"
      }
    },
    "pages": {
      "home": "Startseite",
      "login": "Anmeldung",
      "registration": "Registrierung",
      "settings": "Einstellungen",
      "patients": {
        "create": "Neuen Klienten registrieren",
        "details": "Klientendetails",
        "conversations": "Gesprächszusammenfassung",
        "interactions": "Klienteninteraktionen"
      },
      "chatbot": {
        "create": "Neuen Chatbot erstellen",
        "details": "Chatbot-Details"
      },
      "meetings": {
        "create": "Neues Meeting erstellen",
        "details": "Meeting-Details"
      },
      "gad7": {
        "create": "GAD-7-Bewertung"
      },
      "exercises": {
        "create": "Übung erstellen",
        "details": "Übungsdetails"
      },
      "chatbot_templates": {
        "create": "Neue Chatbot-Vorlage erstellen",
        "details": "Chatbot-Vorlagendetails"
      },
      "counseling_plan": {
        "details": "Behandlungsplan"
      },
      "not_found": "Nicht gefunden"
    }
  },
  "en": {
    "header": {
      "title": "This is the header",
      "subtitle": "These are the current pages:",
      "dashboard": "Dashboard Page",
      "register": "Register Page",
      "login": "Login Page",
      "patients": "Patient Overview Page",
      "patient_detail": "Example Patient Detail Page for ID: \"{{id}}\"",
      "patient_create_bot": "Example Patient Create Bot Page",
      "bot_edit": "Example Bot Edit Page for Bot ID: \"{{id}}\"",
      "create_bot_template": "Create ChatBot Template Page",
      "edit_bot_template": "Edit ChatBot Template for ID: \"{{id}}\"",
      "settings": "Settings Page"
    },
    "footer": {
      "title": "This is the footer",
      "note": "Ask your personal assistant..."
    },
    "settings": {
      "title": "Settings",
      "language": "Language",
      "changePasswordTitle": "Change password",
      "newPassword": "New password",
      "confirmNewPassword": "Confirm new password",
      "changePasswordButton": "Submit"
    },
    "layout": {
      "dashboard": "Dashboard",
      "dashboards": "Dashboards",
      "general": "General",
      "settings": "Settings",
      "patients": "Clients",
      "list_patients": "List Clients",
      "create_patient": "Create Client",
      "patient_details": "Client Details",
      "logout": "Log Out",
      "overview": "Overview",
      "account": "Account"
    },
    "dashboard": {
      "patient_register_success": "Client registered successfully.",
      "register_new_patient": "Register a new client",
      "add_patient": "Add Client",
      "patients": "Clients",
      "patient_id": "Client ID",
      "no_patients_found": "No Clients found",
      "new_patient": "New Client",
      "enter_information_register_new_patient": "Enter information to register a new client.",
      "patient_name": "Client Name",
      "patient_gender": "Gender",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_age": "Age",
      "patient_phone_number": "Phone Number",
      "patient_email": "E-mail",
      "patient_address": "Address",
      "patient_description": "Client Description",
      "cancel": "Cancel",
      "register": "Register",
      "rename": "Rename",
      "clone": "Clone",
      "delete": "Delete",
      "save": "Save",
      "welcome_message": "You are logged in as: ",
      "upload_file": "Upload File",
      "chatbot_cloned_success": "Chatbot cloned successfully.",
      "chatbot_deleted_success": "Chatbot deleted successfully.",
      "create_bot": "Create Chatbot Template",
      "your_chatbot_templates": "Your Chatbot Templates",
      "unnamed_bot": "Unnamed Bot",
      "no_welcome_message_set": "No welcome message set",
      "no_chatbots_created_yet": "No chatbots created yet.",
      "role": "Role",
      "your_files": "Your Files"
    },
    "chatbot": {
      "chatbots": "Chatbots",
      "chatbot_created_success": "Chatbot created successfully.",
      "chatbot_updated_success": "Chatbot updated successfully.",
      "chatbot_named_success": "Chatbot renamed successfully.",
      "create_new_chatbot_template": "Create new chatbot template",
      "create_chatbot_from_template": "Create Chatbot from Template",
      "create_new_chatbot": "Create New Chatbot",
      "new_bot": "New Bot",
      "no_chatbots_created_yet": "You haven't created any chatbots yet.",
      "client_chatbot": "Client Chatbot",
      "client_chatbots": "Client Chatbots",
      "conversation_summary": "Conversation Summary",
      "what_would_you_like_to_name_your_bot": "What would you like to name your bot?",
      "enter_bot_name": "Enter bot name",
      "rename_bot": "Rename Bot",
      "enter_new_name_for_bot": "Enter the new name for your bot.",
      "enter_new_bot_name": "Enter new bot name",
      "template_not_leaded_yet": "Template not loaded yet.",
      "chat_service_unavailable": "Chat service is currently unavailable.",
      "chatbot_configuration": "Chatbot Configuration",
      "name": "Name",
      "role": "Role",
      "faq": "FAQ",
      "supportive": "Supportive",
      "counseling": "Counseling",
      "self_help": "Self-Help",
      "undefined": "Undefined",
      "language": "Language",
      "english": "English",
      "german": "German",
      "french": "French",
      "spanish": "Spanish",
      "chatbot_icon": "Chatbot Icon",
      "chatbot": "Chatbot",
      "robot": "Robot",
      "person": "Person",
      "bulb": "Bulb",
      "book": "Book",
      "voice": "Voice",
      "none": "None",
      "male_voice": "Male Voice",
      "female_voice": "Female Voice",
      "robotic_voice": "Robotic Voice",
      "gender": "Gender",
      "neutral": "Neutral",
      "male": "Male",
      "female": "Female",
      "conversation_tone": "Conversation Tone",
      "friendly": "Friendly",
      "formal": "Formal",
      "casual": "Casual",
      "professional": "Professional",
      "preconfigured_exercise": "Pre-configured Exercise",
      "breathing_exercise": "Breathing Exercise",
      "journaling": "Journaling",
      "relaxation_technique": "Relaxation Technique",
      "additional_exercise": "Additional Exercise",
      "meditation_practise": "Meditation Practice",
      "cbt_example": "CBT Example",
      "animation": "Animation",
      "simple": "Simple",
      "advanced": "Advanced",
      "welcome_message": "Welcome Message",
      "chatbot_input_placeholder": "Chatbot Input Placeholder",
      "simulation": "Simulation",
      "you": "You",
      "type_your_message": "Type a message...",
      "analytics": "Analytics",
      "total_chats": "Total Chats (Threads)",
      "thread_id": "Thread ID",
      "no_threads_found": "No threads found.",
      "template_files": "Template Files"
    },
    "counseling_plan": {
      "add_existing_exercise": "Add Existing Exercise",
      "create_new_exercise": "Create New Exercise",
      "exercise": "Exercise",
      "title": "Title",
      "exercises": "Exercises",
      "cancel": "Cancel",
      "start_date": "Start Date",
      "end_date": "End Date",
      "duration": "Duration",
      "weeks": "Weeks",
      "goals": "Goals",
      "add_a_phase": "Add a Phase",
      "phase_name": "Phase Name",
      "duration_in_weeks": "Duration in Weeks",
      "create_phase": "Create Phase",
      "make_ai_generated_suggestion": "Make AI generated suggestion",
      "exercise_title": "Exercise Title",
      "exercise_type": "Exercise Type",
      "exercise_start": "Exercise Start",
      "add_a_goal": "Add a Goal",
      "goal_name": "Goal Name",
      "goal_description": "Goal Description",
      "make_ai_generated_suggestion_for_goal": "Make AI generated suggestion for goal",
      "make_ai_generated_suggestion_for_phase": "Make AI generated suggestion for phase",
      "make_ai_generated_suggestion_for_exercise": "Make AI generated suggestion for exercise",
      "create_goal": "Create Goal",
      "counseling_start_date": "Counseling Start Date",
      "counseling_plan_phases": "Counseling Plan Phases"
    },
    "exercise": {
      "upload_image": "Upload Image",
      "description": "Description",
      "add_input_field": "Add Input Field",
      "description_of_input": "Description of Input",
      "add_text": "Add Text",
      "text": "Text",
      "create_new_exercise": "Create New Exercise",
      "exercise": "Exercise",
      "exercise_type": "Exercise Type",
      "exercise_start": "Exercise Start",
      "duration_in_weeks": "Duration in Weeks",
      "exercise_end": "Exercise End",
      "is_paused": "Is Paused",
      "is_currently_paused": "Is Currently Paused",
      "is_exercise_paused": "Is Exercise Paused",
      "no_exercises_yet": "You haven't added any exercises yet...",
      "no_exercise_components_yet": "You haven't added any exercise components yet...",
      "image": "Image",
      "file": "File",
      "input_field": "Input Field",
      "order": "Order",
      "desciption_of_input": "Description of Input",
      "title": "Title",
      "submit": "Submit",
      "cancel": "Cancel",
      "edit_exercise": "Edit Exercise",
      "exercise_components": "Exercise Components",
      "delete_exercise": "Delete Exercise"
    },
    "not_found": {
      "title": "404 - Page Not Found",
      "message": "Oops! The page you're looking for doesn't exist."
    },
    "patient_detail": {
      "message": "This is the client detail page of client with ID",
      "view_client_interactions": "View Client Interactions",
      "client": "Client",
      "email_client_app": "Email (for Login in Client App)",
      "initial_password_client_app": "Initial Password (for Login in Client App)",
      "client_app_link": "Client App Link",
      "age": "Age",
      "gender": "Gender",
      "phone": "Phone",
      "address": "Address",
      "date_of_admission": "Date of Admission",
      "view_more_details": "View more Details",
      "loading_patient_data": "Loading Patient Data...",
      "counseling_plan": "Counseling Plan",
      "go_to_counseling_plan": "Go to Counseling Plan",
      "current_phase": "Current Phase",
      "currently_no_phase_is_active": "Currently no phase is active.",
      "create_a_new_chatbot": "Create a new Chatbot",
      "please_enter_name_for_chatbot": "Please enter a name for your new chatbot",
      "chatbot_name": "Chabot Name",
      "create_bot": "Create Bot",
      "files_visible_to_client": "Files visible to Client",
      "files_visible_only_to_coach": "Files visible only to Coach"
    },
    "patient_interactions": {
      "interaction_type": "Interaction Type",
      "start_date": "Start Date",
      "end_date": "End Date",
      "time": "Time",
      "date": "Date"
    },
    "patient_create": {
      "title": "This is the page to create a new client",
      "new_patient": "New client",
      "create_patient": "Create client",
      "patient_name": "Name",
      "patient_age": "Age",
      "patient_gender": "Sex",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_marital_status": "Marital Status",
      "patient_religion": "Religion",
      "patient_education": "Education",
      "patient_occupation": "Occupation",
      "patient_income": "Income",
      "patient_address": "Address",
      "patient_phone": "Phone Number",
      "patient_email": "Email",
      "patient_date_of_admission": "Date of Admission",
      "register": "Register",
      "cancel": "Cancel",
      "complaint": "Complaint",
      "main_complaints": "Main Complaints",
      "history_of_present_illness": "History of Present Illness",
      "hpi_duration": "Duration",
      "hpi_onset": "Onset",
      "onset_abrupt": "Abrupt",
      "onset_acute": "Acute",
      "onset_subacute": "Subacute",
      "onset_insidious": "Insidious",
      "hpi_course": "Course",
      "hpi_course_continuous": "Continuous",
      "hpi_course_episodic": "Episodic",
      "hpi_course_fluctuating": "Fluctuating",
      "hpi_course_deteriorating": "Deteriorating",
      "hpi_course_improving": "Improving",
      "hpi_course_unclear": "Unclear",
      "hpi_precipitating_factors": "Precipitating Factors",
      "hpi_aggravating_relieving": "Aggravating and Relieving Factors",
      "hpi_aggravating_relieving_placeholder": "What makes it better or worse?",
      "hpi_timeline": "Timeline",
      "hpi_timeline_placeholder": "Describe how the symptoms evolved over time.",
      "hpi_advanced_details": "Advanced HPI Details",
      "hpi_disturbances": "Disturbances in sleep, appetite, energy, etc.",
      "hpi_disturbances_placeholder": "e.g., insomnia, fatigue, weight change",
      "hpi_suicidal_ideation": "Suicidal Thoughts or Behaviors",
      "yes_no_explanation": "Yes/No with brief explanation",
      "hpi_negative_history": "Relevant Negative History",
      "hpi_negative_history_placeholder": "Mention conditions that are not present",
      "history_present_illness": "History of Present Illness",
      "hpi_general_info": "General Information",
      "hpi_onset_abrupt": "Abrupt",
      "hpi_onset_acute": "Acute",
      "hpi_onset_subacute": "Subacute",
      "hpi_onset_insidious": "Insidious",
      "hpi_symptom_timeline": "Symptom Timeline",
      "add_another_complaint": "Add Another Complaint",
      "treatment_history": "Treatment History",
      "treatment_past": "Past Treatments",
      "treatment_current": "Current Treatments",
      "past_history": "Past History",
      "past_medical": "Past Medical History",
      "past_psych": "Past Psychiatric History",
      "family_history": "Family History",
      "family_illness": "Family Illnesses",
      "family_social": "Family Social Background",
      "personal_history": "Personal History",
      "personal_perinatal": "Perinatal History",
      "personal_childhood": "Childhood History",
      "personal_education": "Educational History",
      "personal_play": "Play and Social History",
      "personal_adolescence": "Adolescence History",
      "personal_puberty": "Puberty and Sexual History",
      "personal_obstetric": "Obstetric History",
      "personal_occupational": "Occupational History",
      "personal_marital": "Marital and Relationship History",
      "personal_premorbid": "Premorbid Personality",
      "patient_register_success": "Client registered successfully.",
      "patient_register_failed": "Failed to register client. Please try again."
    },
    "register": {
      "welcome": "Welcome to the Therapist App",
      "register_therapist": "Register as a new Therapist",
      "email": "Email",
      "password": "Password",
      "register": "Register",
      "go_login": "Go to the Login instead"
    },
    "login": {
      "welcome": "Welcome to the Therapist App",
      "login_therapist": "Login as a Therapist",
      "email": "Email",
      "password": "Password",
      "login": "Login",
      "go_registration": "Go to Registration instead"
    },
    "meetings": {
      "meetings": "Meetings",
      "meeting_start": "Meeting Start",
      "meeting_end": "Meeting End",
      "meeting_location": "Meeting Location",
      "duration": "Duration",
      "duration_in_minutes": "Duration in Minutes",
      "minutes": "minutes",
      "location": "Location",
      "create_meeting": "Create Meeting",
      "create_new_note": "Create New Note",
      "transcribe_meeting": "Transcribe Meeting",
      "meeting_transcription": "Meeting Transcription",
      "new_note": "New Note",
      "title": "Title",
      "language": "Language",
      "content": "Content (Type or Speak)",
      "speak_or_type_here": "Speak or type here...",
      "start_listening": "Start Listening",
      "listening": "Listening...",
      "listening_speak_into_microphone": "Listening... Speak into your microphone.",
      "stop_listening": "Stop Listening",
      "no_notes_yet": "You don't have any notes yet.",
      "delete_meeting": "Delete Meeting",
      "browser_compatibility": "Browser Compatibility",
      "web_search_api_not_supported": "Web Speech API is not supported in your browser. Please try Chrome or Edge for the best experience.",
      "error": {
        "error": "Error",
        "no_speech_detected": "No speech detected. Please try speaking a bit louder or clearer.",
        "microphone_not_available": "Microphone not available or permission denied. Please check your microphone settings and browser permissions.",
        "not_allowed": "Permission to use the microphone was denied or has not been granted. Please allow microphone access in your browser settings."
      },
      "save": "Save",
      "cancel": "Cancel",
      "CONFIRMED": "Confirmed",
      "CANCELLED": "Cancelled",
      "PENDING": "Pending",
      "editMeeting": "Edit Meeting",
      "meetingStatus": "Meeting Status",
      "yourNotes": "Your Notes"
    },
    "gad7test": {
      "title": "GAD-7 Assessment",
      "gad7tests": "GAD-7 Tests",
      "create_gad7test": "Create GAD-7 Test",
      "description": "Over the last 2 weeks, how often have you been bothered by the following problems?",
      "question1": "Feeling nervous, anxious or on edge.",
      "question2": "Not being able to stop or control worrying.",
      "question3": "Worrying too much about different things.",
      "question4": "Trouble relaxing.",
      "question5": "Being so restless that it is hard to sit still.",
      "question6": "Becoming easily annoyed or irritable.",
      "question7": "Feeling afraid as if something awful might happen.",
      "total_score": "Total Score",
      "cancel": "Cancel",
      "submit": "Submit",
      "no_tests_yet": "You haven't created any GAD-7 tests yet.",
      "answers": {
        "not_at_all": "Not at all",
        "several_days": "Several days",
        "more_than_half_the_days": "More than half the days",
        "nearly_everyday": "Nearly every day"
      }
    },
    "pages": {
      "home": "Home",
      "login": "Login",
      "registration": "Registration",
      "settings": "Settings",
      "patients": {
        "create": "Register new Client",
        "details": "Client Details",
        "conversations": "Conversation Summary",
        "interactions": "Client Interactions"
      },
      "chatbot": {
        "create": "Create new Chatbot",
        "details": "Chatbot Details"
      },
      "meetings": {
        "create": "Create new Meeting",
        "details": "Meeting Details"
      },
      "gad7": {
        "create": "GAD-7 Assessment"
      },
      "exercises": {
        "create": "Create Exercise",
        "details": "Exercise Details"
      },
      "chatbot_templates": {
        "create": "Create new Chatbot Template",
        "details": "Chatbot Template Details"
      },
      "counseling_plan": {
        "details": "Counseling Plan"
      },
      "not_found": "Not Found"
    }
  },
  "ua": {
    "header": {
      "title": "Це заголовок",
      "subtitle": "Поточні сторінки:",
      "dashboard": "Панель керування",
      "register": "Сторінка реєстрації",
      "login": "Сторінка входу",
      "patients": "Огляд пацієнтів",
      "patient_detail": "Сторінка деталей пацієнта з ID: \"{{id}}\"",
      "patient_create_bot": "Сторінка створення бота для пацієнта",
      "bot_edit": "Сторінка редагування бота з ID: \"{{id}}\"",
      "create_bot_template": "Сторінка створення шаблону чат-бота",
      "edit_bot_template": "Редагування шаблону чат-бота з ID: \"{{id}}\"",
      "settings": "Налаштування"
    },
    "footer": {
      "title": "Це підвал",
      "note": "Запитайте свого персонального помічника..."
    },
    "settings": {
      "title": "Налаштування",
      "language": "Мова",
      "changePasswordTitle": "Змінити пароль",
      "newPassword": "Новий пароль",
      "confirmNewPassword": "Підтвердити новий пароль",
      "changePasswordButton": "Підтвердити"
    },
    "layout": {
      "dashboard": "Панель керування",
      "dashboards": "Панелі",
      "general": "Загальне",
      "settings": "Налаштування",
      "patients": "Клієнти",
      "list_patients": "Список клієнтів",
      "create_patient": "Створити клієнта",
      "patient_details": "Деталі клієнта",
      "logout": "Вийти",
      "overview": "Огляд",
      "account": "Акаунт"
    },
    "dashboard": {
      "patient_register_success": "Клієнта успішно зареєстровано.",
      "register_new_patient": "Зареєструвати нового клієнта",
      "add_patient": "Додати клієнта",
      "patients": "Клієнти",
      "patient_id": "ID клієнта",
      "no_patients_found": "Клієнтів не знайдено",
      "new_patient": "Новий клієнт",
      "enter_information_register_new_patient": "Введіть інформацію для реєстрації нового клієнта.",
      "patient_name": "Ім'я клієнта",
      "patient_gender": "Стать",
      "male": "Чоловік",
      "female": "Жінка",
      "other": "Інше",
      "patient_age": "Вік",
      "patient_phone_number": "Номер телефону",
      "patient_email": "Електронна пошта",
      "patient_address": "Адреса",
      "patient_description": "Опис клієнта",
      "cancel": "Скасувати",
      "register": "Зареєструвати",
      "rename": "Перейменувати",
      "clone": "Клонувати",
      "delete": "Видалити",
      "save": "Зберегти",
      "welcome_message": "Ви ввійшли як: ",
      "upload_file": "Завантажити файл",
      "chatbot_cloned_success": "Чат-бота успішно клоновано.",
      "chatbot_deleted_success": "Чат-бота успішно видалено.",
      "create_bot": "Створити шаблон чат-бота",
      "your_chatbot_templates": "Ваші шаблони чат-ботів",
      "unnamed_bot": "Без назви",
      "no_welcome_message_set": "Привітальне повідомлення не встановлено",
      "no_chatbots_created_yet": "Ще не створено жодного чат-бота.",
      "role": "Роль",
      "your_files": "Ваші файли"
    },
    "chatbot": {
      "chatbots": "Чат-боти",
      "chatbot_created_success": "Чат-бота успішно створено.",
      "chatbot_updated_success": "Чат-бота успішно оновлено.",
      "chatbot_named_success": "Чат-бота успішно перейменовано.",
      "create_new_chatbot_template": "Створити новий шаблон чат-бота",
      "create_chatbot_from_template": "Створити чат-бота з шаблону",
      "create_new_chatbot": "Створити нового чат-бота",
      "new_bot": "Новий бот",
      "no_chatbots_created_yet": "Ви ще не створили жодного чат-бота.",
      "client_chatbot": "Клієнтський чат-бот",
      "client_chatbots": "Клієнтські чат-боти",
      "conversation_summary": "Підсумок розмови",
      "what_would_you_like_to_name_your_bot": "Як ви хочете назвати свого бота?",
      "enter_bot_name": "Введіть назву бота",
      "rename_bot": "Перейменувати бота",
      "enter_new_name_for_bot": "Введіть нову назву для вашого бота.",
      "enter_new_bot_name": "Введіть нову назву бота",
      "template_not_leaded_yet": "Шаблон ще не завантажено.",
      "chat_service_unavailable": "Чат-сервіс тимчасово недоступний.",
      "chatbot_configuration": "Налаштування чат-бота",
      "name": "Назва",
      "role": "Роль",
      "faq": "FAQ",
      "supportive": "Підтримка",
      "counseling": "Консультування",
      "self_help": "Самодопомога",
      "undefined": "Не визначено",
      "language": "Мова",
      "english": "Англійська",
      "german": "Німецька",
      "french": "Французька",
      "spanish": "Іспанська",
      "chatbot_icon": "Іконка чат-бота",
      "chatbot": "Чат-бот",
      "robot": "Робот",
      "person": "Людина",
      "bulb": "Лампочка",
      "book": "Книга",
      "voice": "Голос",
      "none": "Немає",
      "male_voice": "Чоловічий голос",
      "female_voice": "Жіночий голос",
      "robotic_voice": "Роботизований голос",
      "gender": "Стать",
      "neutral": "Нейтральний",
      "male": "Чоловік",
      "female": "Жінка",
      "conversation_tone": "Тон розмови",
      "friendly": "Дружній",
      "formal": "Офіційний",
      "casual": "Невимушений",
      "professional": "Професійний",
      "preconfigured_exercise": "Попередньо налаштована вправа",
      "breathing_exercise": "Дихальна вправа",
      "journaling": "Ведення щоденника",
      "relaxation_technique": "Техніка релаксації",
      "additional_exercise": "Додаткова вправа",
      "meditation_practise": "Медитація",
      "cbt_example": "Приклад КПТ",
      "animation": "Анімація",
      "simple": "Проста",
      "advanced": "Розширена",
      "welcome_message": "Привітальне повідомлення",
      "chatbot_input_placeholder": "Поле вводу для чат-бота",
      "simulation": "Симуляція",
      "you": "Ви",
      "type_your_message": "Введіть повідомлення...",
      "analytics": "Аналітика",
      "total_chats": "Всього чатів (тем)",
      "thread_id": "ID теми",
      "no_threads_found": "Тем не знайдено.",
      "template_files": "Файли шаблонів"
    },
    "counseling_plan": {
      "add_existing_exercise": "Додати існуючу вправу",
      "create_new_exercise": "Створити нову вправу",
      "exercise": "Вправа",
      "title": "Назва",
      "exercises": "Вправи",
      "cancel": "Скасувати",
      "start_date": "Дата початку",
      "end_date": "Дата завершення",
      "duration": "Тривалість",
      "weeks": "Тижні",
      "goals": "Цілі",
      "add_a_phase": "Додати фазу",
      "phase_name": "Назва фази",
      "duration_in_weeks": "Тривалість у тижнях",
      "create_phase": "Створити фазу",
      "make_ai_generated_suggestion": "Зробити AI-пропозицію",
      "exercise_title": "Назва вправи",
      "exercise_type": "Тип вправи",
      "exercise_start": "Початок вправи",
      "add_a_goal": "Додати ціль",
      "goal_name": "Назва цілі",
      "goal_description": "Опис цілі",
      "create_goal": "Створити ціль",
      "make_ai_generated_suggestion_for_goal": "Зробити AI-пропозицію для цілі",
      "make_ai_generated_suggestion_for_phase": "Зробити AI-пропозицію для фази",
      "make_ai_generated_suggestion_for_exercise": "Зробити AI-пропозицію для вправи",
      "counseling_start_date": "Дата початку консультування",
      "counseling_plan_phases": "Фази плану консультування"
    },
    "exercise": {
      "upload_image": "Завантажити зображення",
      "description": "Опис",
      "add_input_field": "Додати поле вводу",
      "description_of_input": "Опис вводу",
      "add_text": "Додати текст",
      "text": "Текст",
      "create_new_exercise": "Створити нову вправу",
      "exercise": "Вправа",
      "exercise_type": "Тип вправи",
      "exercise_start": "Початок вправи",
      "duration_in_weeks": "Тривалість у тижнях",
      "exercise_end": "Завершення вправи",
      "is_paused": "Призупинено",
      "is_currently_paused": "Зараз призупинено",
      "is_exercise_paused": "Чи призупинено вправу",
      "no_exercises_yet": "Ви ще не додали жодної вправи...",
      "no_exercise_components_yet": "Ви ще не додали жодного компоненту вправи...",
      "image": "Зображення",
      "file": "Файл",
      "input_field": "Поле вводу",
      "order": "Порядок",
      "desciption_of_input": "Опис вводу",
      "title": "Назва",
      "submit": "Надіслати",
      "cancel": "Скасувати",
      "edit_exercise": "Редагувати вправу",
      "exercise_components": "Компоненти вправи",
      "delete_exercise": "Видалити вправу"
    },
    "not_found": {
      "title": "404 - Сторінку не знайдено",
      "message": "Ой! Сторінка, яку ви шукаєте, не існує."
    },
    "patient_detail": {
      "message": "Це сторінка деталей клієнта з ID",
      "view_client_interactions": "Переглянути взаємодії клієнта",
      "client": "Клієнт",
      "email_client_app": "Email (для входу в клієнтський додаток)",
      "initial_password_client_app": "Початковий пароль (для входу в клієнтський додаток)",
      "client_app_link": "Посилання на клієнтський додаток",
      "age": "Вік",
      "gender": "Стать",
      "phone": "Телефон",
      "address": "Адреса",
      "date_of_admission": "Дата прийому",
      "view_more_details": "Переглянути більше деталей",
      "loading_patient_data": "Завантаження даних пацієнта...",
      "counseling_plan": "План консультування",
      "go_to_counseling_plan": "Перейти до плану консультування",
      "current_phase": "Поточна фаза",
      "currently_no_phase_is_active": "Наразі немає активної фази.",
      "create_a_new_chatbot": "Створити нового чат-бота",
      "please_enter_name_for_chatbot": "Будь ласка, введіть назву для вашого нового чат-бота",
      "chatbot_name": "Назва чат-бота",
      "create_bot": "Створити бота",
      "files_visible_to_client": "Файли, видимі клієнту",
      "files_visible_only_to_coach": "Файли, видимі тільки тренеру"
    },
    "patient_interactions": {
      "interaction_type": "Тип взаємодії",
      "start_date": "Дата початку",
      "end_date": "Дата завершення",
      "time": "Час",
      "date": "Дата"
    },
    "patient_create": {
      "title": "Це сторінка створення нового клієнта",
      "new_patient": "Новий клієнт",
      "create_patient": "Створити клієнта",
      "patient_name": "Ім'я",
      "patient_age": "Вік",
      "patient_gender": "Стать",
      "male": "Чоловік",
      "female": "Жінка",
      "other": "Інше",
      "patient_marital_status": "Сімейний стан",
      "patient_religion": "Релігія",
      "patient_education": "Освіта",
      "patient_occupation": "Рід занять",
      "patient_income": "Дохід",
      "patient_address": "Адреса",
      "patient_phone": "Номер телефону",
      "patient_email": "Email",
      "patient_date_of_admission": "Дата прийому",
      "register": "Зареєструвати",
      "cancel": "Скасувати",
      "complaint": "Скарга",
      "main_complaints": "Основні скарги",
      "history_of_present_illness": "Історія теперішньої хвороби",
      "hpi_duration": "Тривалість",
      "hpi_onset": "Початок",
      "onset_abrupt": "Раптовий",
      "onset_acute": "Гострий",
      "onset_subacute": "Підгострий",
      "onset_insidious": "Поступовий",
      "hpi_course": "Перебіг",
      "hpi_course_continuous": "Безперервний",
      "hpi_course_episodic": "Епізодичний",
      "hpi_course_fluctuating": "Коливальний",
      "hpi_course_deteriorating": "Погіршуючий",
      "hpi_course_improving": "Покращуючий",
      "hpi_course_unclear": "Неясний",
      "hpi_precipitating_factors": "Чинники, що спровокували",
      "hpi_aggravating_relieving": "Чинники, що погіршують і полегшують",
      "hpi_aggravating_relieving_placeholder": "Що покращує або погіршує стан?",
      "hpi_timeline": "Хронологія",
      "hpi_timeline_placeholder": "Опишіть, як розвивалися симптоми з часом.",
      "hpi_advanced_details": "Детальна інформація",
      "hpi_disturbances": "Порушення сну, апетиту, енергії тощо",
      "hpi_disturbances_placeholder": "напр., безсоння, втома, зміна ваги",
      "hpi_suicidal_ideation": "Суїцидальні думки чи поведінка",
      "yes_no_explanation": "Так/Ні з коротким поясненням",
      "hpi_negative_history": "Відсутність супутніх захворювань",
      "hpi_negative_history_placeholder": "Вкажіть захворювання, яких немає",
      "history_present_illness": "Історія теперішньої хвороби",
      "hpi_general_info": "Загальна інформація",
      "hpi_onset_abrupt": "Раптовий",
      "hpi_onset_acute": "Гострий",
      "hpi_onset_subacute": "Підгострий",
      "hpi_onset_insidious": "Поступовий",
      "hpi_symptom_timeline": "Хронологія симптомів",
      "add_another_complaint": "Додати ще одну скаргу",
      "treatment_history": "Історія лікування",
      "treatment_past": "Попереднє лікування",
      "treatment_current": "Поточне лікування",
      "past_history": "Минула історія",
      "past_medical": "Медична історія",
      "past_psych": "Психіатрична історія",
      "family_history": "Сімейна історія",
      "family_illness": "Сімейні захворювання",
      "family_social": "Соціальний сімейний анамнез",
      "personal_history": "Особиста історія",
      "personal_perinatal": "Перинатальний анамнез",
      "personal_childhood": "Дитинство",
      "personal_education": "Освіта",
      "personal_play": "Ігри та соціальний розвиток",
      "personal_adolescence": "Підлітковий вік",
      "personal_puberty": "Статеве дозрівання",
      "personal_obstetric": "Акушерський анамнез",
      "personal_occupational": "Професійна історія",
      "personal_marital": "Шлюб та стосунки",
      "personal_premorbid": "Преморбідна особистість",
      "patient_register_success": "Клієнта успішно зареєстровано.",
      "patient_register_failed": "Не вдалося зареєструвати клієнта. Спробуйте ще раз."
    },
    "register": {
      "welcome": "Ласкаво просимо до додатку терапевта",
      "register_therapist": "Зареєструватися як новий терапевт",
      "email": "Email",
      "password": "Пароль",
      "register": "Зареєструватися",
      "go_login": "Перейти до входу"
    },
    "login": {
      "welcome": "Ласкаво просимо до додатку терапевта",
      "login_therapist": "Увійти як терапевт",
      "email": "Email",
      "password": "Пароль",
      "login": "Увійти",
      "go_registration": "Перейти до реєстрації"
    },
    "meetings": {
      "meetings": "Зустрічі",
      "meeting_start": "Початок зустрічі",
      "meeting_end": "Кінець зустрічі",
      "meeting_location": "Місце зустрічі",
      "duration": "Тривалість",
      "duration_in_minutes": "Тривалість у хвилинах",
      "minutes": "хвилин",
      "location": "Місце",
      "create_meeting": "Створити зустріч",
      "create_new_note": "Створити нову нотатку",
      "transcribe_meeting": "Транскрибувати зустріч",
      "meeting_transcription": "Транскрипція зустрічі",
      "new_note": "Нова нотатка",
      "title": "Назва",
      "language": "Мова",
      "content": "Вміст (друк або голос)",
      "speak_or_type_here": "Говоріть або друкуйте тут...",
      "start_listening": "Почати запис",
      "listening": "Запис...",
      "listening_speak_into_microphone": "Запис... Говоріть у мікрофон.",
      "stop_listening": "Зупинити запис",
      "no_notes_yet": "У вас ще немає нотаток.",
      "delete_meeting": "Видалити зустріч",
      "browser_compatibility": "Сумісність браузера",
      "web_search_api_not_supported": "Web Speech API не підтримується у вашому браузері. Спробуйте Chrome або Edge для кращого досвіду.",
      "error": {
        "error": "Помилка",
        "no_speech_detected": "Мова не розпізнана. Будь ласка, говоріть голосніше або чіткіше.",
        "microphone_not_available": "Мікрофон недоступний або дозвіл відхилено. Перевірте налаштування мікрофона та дозволи браузера.",
        "not_allowed": "Дозвіл на використання мікрофона відхилено або не надано. Дозвольте доступ до мікрофона в налаштуваннях браузера."
      },
      "save": "Зберегти",
      "cancel": "Скасувати",
      "CONFIRMED": "Підтверджено",
      "CANCELLED": "Скасовано",
      "PENDING": "Очікує",
      "editMeeting": "Редагувати зустріч",
      "meetingStatus": "Статус зустрічі",
      "yourNotes": "Ваші нотатки"
    },
    "gad7test": {
      "title": "Опитування GAD-7",
      "gad7tests": "Тести GAD-7",
      "create_gad7test": "Створити тест GAD-7",
      "description": "Як часто вас турбували наступні проблеми протягом останніх 2 тижнів?",
      "question1": "Нервозність, тривога або напруга.",
      "question2": "Неможливість припинити або контролювати занепокоєння.",
      "question3": "Надмірне занепокоєння з різних причин.",
      "question4": "Труднощі з розслабленням.",
      "question5": "Непосидючість через тривогу.",
      "question6": "Легка дратівливість.",
      "question7": "Відчуття страху, ніби має статися щось погане.",
      "total_score": "Загальний бал",
      "cancel": "Скасувати",
      "submit": "Надіслати",
      "no_tests_yet": "Ви ще не створили жодного тесту GAD-7.",
      "answers": {
        "not_at_all": "Зовсім ні",
        "several_days": "Кілька днів",
        "more_than_half_the_days": "Більше половини днів",
        "nearly_everyday": "Майже щодня"
      }
    },
    "pages": {
      "home": "Головна",
      "login": "Вхід",
      "registration": "Реєстрація",
      "settings": "Налаштування",
      "patients": {
        "create": "Зареєструвати нового клієнта",
        "details": "Деталі клієнта",
        "conversations": "Підсумок бесід",
        "interactions": "Взаємодії з клієнтом"
      },
      "chatbot": {
        "create": "Створити нового чат-бота",
        "details": "Деталі чат-бота"
      },
      "meetings": {
        "create": "Створити нову зустріч",
        "details": "Деталі зустрічі"
      },
      "gad7": {
        "create": "Опитування GAD-7"
      },
      "exercises": {
        "create": "Створити вправу",
        "details": "Деталі вправи"
      },
      "chatbot_templates": {
        "create": "Створити новий шаблон чат-бота",
        "details": "Деталі шаблону чат-бота"
      },
      "counseling_plan": {
        "details": "План консультування"
      },
      "not_found": "Не знайдено"
    }
  }
}

export default Resources;
