interface Resources {
  "en": {
    "header": {
      "title": "This is the header",
      "subtitle": "These are the current pages:",
      "dashboard": "Dashboard Page",
      "register": "Register Page",
      "login": "Login Page",
      "patients": "Patient Overview Page",
      "patient_detail": "Example Patient Detail Page for ID: \"{{id}}\"",
      "patient_create_bot": "Example Patient Create Bot Page",
      "bot_edit": "Example Bot Edit Page for Bot ID: \"{{id}}\"",
      "create_bot_template": "Create ChatBot Template Page",
      "edit_bot_template": "Edit ChatBot Template for ID: \"{{id}}\"",
      "settings": "Settings Page"
    },
    "footer": {
      "title": "This is the footer",
      "note": "Ask your personal assistant..."
    },
    "settings": {
      "title": "Settings",
      "language": "Language"
    },
    "layout": {
      "dashboard": "Dashboard",
      "dashboards": "Dashboards",
      "general": "General",
      "settings": "Settings",
      "patients": "Clients",
      "list_patients": "List Clients",
      "create_patient": "Create Client",
      "patient_details": "Client Details",
      "logout": "Log Out",
      "overview": "Overview",
      "account": "Account"
    },
    "dashboard": {
      "patient_register_success": "Client registered successfully.",
      "chatbot_created_success": "Chatbot created successfully.",
      "chatbot_named_success": "Chatbot renamed successfully.",
      "chatbot_cloned_success": "Chatbot cloned successfully.",
      "chatbot_deleted_success": "Chatbot deleted successfully.",
      "register_new_patient": "Register a new client",
      "add_patient": "Add Client",
      "patients": "Clients",
      "patient_id": "Client ID",
      "no_patients_found": "No Clients found",
      "new_patient": "New Client",
      "enter_information_register_new_patient": "Enter information to register a new client.",
      "patient_name": "Client Name",
      "patient_gender": "Gender",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_age": "Age",
      "patient_phone_number": "Phone Number",
      "patient_email": "E-mail",
      "patient_address": "Address",
      "patient_description": "Client Description",
      "cancel": "Cancel",
      "register": "Register",
      "create_new_chatbot_template": "Create new chatbot template",
      "create_bot": "Create Chatbot Template",
      "your_chatbot_templates": "Your Chatbot Templates",
      "unnamed_bot": "Unnamed Bot",
      "no_welcome_message_set": "No welcome message set",
      "language": "Language",
      "role": "Role",
      "no_chatbots_created_yet": "No chatbots created yet.",
      "rename": "Rename",
      "clone": "Clone",
      "delete": "Delete",
      "save": "Save",
      "new_bot": "New Bot",
      "what_would_you_like_to_name_your_bot": "What would you like to name your bot?",
      "enter_bot_name": "Enter bot name",
      "rename_bot": "Rename Bot",
      "enter_new_name_for_bot": "Enter the new name for your bot.",
      "enter_new_bot_name": "Enter new bot name",
      "welcome_message": "You are logged in as: ",
      "upload_file": "Upload File"
    },
    "not_found": {
      "title": "404 - Page Not Found",
      "message": "Oops! The page you're looking for doesn't exist."
    },
    "patient_detail": {
      "message": "This is the client detail page of client with ID"
    },
    "patient_create": {
      "title": "This is the page to create a new client",
      "new_patient": "New client",
      "create_patient": "Create client",
      "patient_name": "Name",
      "patient_age": "Age",
      "patient_gender": "Sex",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "patient_marital_status": "Marital Status",
      "patient_religion": "Religion",
      "patient_education": "Education",
      "patient_occupation": "Occupation",
      "patient_income": "Income",
      "patient_address": "Address",
      "patient_phone": "Phone Number",
      "patient_email": "Email",
      "patient_date_of_admission": "Date of Admission",
      "register": "Register",
      "cancel": "Cancel",
      "complaint": "Complaint",
      "main_complaints": "Main Complaints",
      "history_of_present_illness": "History of Present Illness",
      "hpi_duration": "Duration",
      "hpi_onset": "Onset",
      "onset_abrupt": "Abrupt",
      "onset_acute": "Acute",
      "onset_subacute": "Subacute",
      "onset_insidious": "Insidious",
      "hpi_course": "Course",
      "hpi_course_continuous": "Continuous",
      "hpi_course_episodic": "Episodic",
      "hpi_course_fluctuating": "Fluctuating",
      "hpi_course_deteriorating": "Deteriorating",
      "hpi_course_improving": "Improving",
      "hpi_course_unclear": "Unclear",
      "hpi_precipitating_factors": "Precipitating Factors",
      "hpi_aggravating_relieving": "Aggravating and Relieving Factors",
      "hpi_aggravating_relieving_placeholder": "What makes it better or worse?",
      "hpi_timeline": "Timeline",
      "hpi_timeline_placeholder": "Describe how the symptoms evolved over time.",
      "hpi_advanced_details": "Advanced HPI Details",
      "hpi_disturbances": "Disturbances in sleep, appetite, energy, etc.",
      "hpi_disturbances_placeholder": "e.g., insomnia, fatigue, weight change",
      "hpi_suicidal_ideation": "Suicidal Thoughts or Behaviors",
      "yes_no_explanation": "Yes/No with brief explanation",
      "hpi_negative_history": "Relevant Negative History",
      "hpi_negative_history_placeholder": "Mention conditions that are not present",
      "history_present_illness": "History of Present Illness",
      "hpi_general_info": "General Information",
      "hpi_onset_abrupt": "Abrupt",
      "hpi_onset_acute": "Acute",
      "hpi_onset_subacute": "Subacute",
      "hpi_onset_insidious": "Insidious",
      "hpi_symptom_timeline": "Symptom Timeline",
      "add_another_complaint": "Add Another Complaint",
      "treatment_history": "Treatment History",
      "treatment_past": "Past Treatments",
      "treatment_current": "Current Treatments",
      "past_history": "Past History",
      "past_medical": "Past Medical History",
      "past_psych": "Past Psychiatric History",
      "family_history": "Family History",
      "family_illness": "Family Illnesses",
      "family_social": "Family Social Background",
      "personal_history": "Personal History",
      "personal_perinatal": "Perinatal History",
      "personal_childhood": "Childhood History",
      "personal_education": "Educational History",
      "personal_play": "Play and Social History",
      "personal_adolescence": "Adolescence History",
      "personal_puberty": "Puberty and Sexual History",
      "personal_obstetric": "Obstetric History",
      "personal_occupational": "Occupational History",
      "personal_marital": "Marital and Relationship History",
      "personal_premorbid": "Premorbid Personality",
      "patient_register_success": "Client registered successfully.",
      "patient_register_failed": "Failed to register client. Please try again."
    },
    "register": {
      "welcome": "Welcome to the Therapist App",
      "register_therapist": "Register as a new Therapist",
      "email": "Email",
      "password": "Password",
      "register": "Register",
      "go_login": "Go to the Login instead"
    },
    "login": {
      "welcome": "Welcome to the Therapist App",
      "login_therapist": "Login as a Therapist",
      "email": "Email",
      "password": "Password",
      "login": "Login",
      "go_registration": "Go to Registration instead"
    },
    "meeting": {
      "new_note": "New Note",
      "title": "Title",
      "language": "Language",
      "content": "Content",
      "speak_or_type_here": "Speak or type here...",
      "start_listening": "Start Listening",
      "listening": "Listening...",
      "listening_speak_into_microphone": "Listening... Speak into your microphone.",
      "stop_listening": "Stop Listening",
      "no_notes_yet": "You don't have any notes yet.",
      "delete_meeting": "Delete Meeting",
      "browser_compatibility": "Browser Compatibility",
      "web_search_api_not_supported": "Web Speech API is not supported in your browser. Please try Chrome or Edge for the best experience.",
      "error": {
        "error": "Error",
        "no_speech_detected": "No speech detected. Please try speaking a bit louder or clearer.",
        "microphone_not_available": "Microphone not available or permission denied. Please check your microphone settings and browser permissions.",
        "not_allowed": "Permission to use the microphone was denied or has not been granted. Please allow microphone access in your browser settings."
      }
    }
  },
  "ua": {
    "header": {
      "title": "Це заголовок",
      "subtitle": "Це поточні сторінки:",
      "dashboard": "Сторінка панелі управління",
      "register": "Сторінка реєстрації",
      "login": "Сторінка входу",
      "patients": "Сторінка огляду пацієнтів",
      "patient_detail": "Приклад сторінки деталей пацієнта для ID: \"{{id}}\"",
      "patient_create_bot": "Приклад сторінки створення бота для пацієнта",
      "bot_edit": "Приклад сторінки редагування бота для Bot ID: \"{{id}}\"",
      "create_bot_template": "Сторінка створення шаблону чат-бота",
      "edit_bot_template": "Сторінка редагування шаблону чат-бота для ID: \"{{id}}\"",
      "settings": "Сторінка налаштувань"
    },
    "footer": {
      "title": "Це підвал"
    },
    "settings": {
      "title": "Налаштування",
      "language": "Мова"
    },
    "layout": {
      "dashboard": "Панель управління",
      "dashboards": "Панелі управління",
      "general": "Загальні",
      "settings": "Налаштування",
      "patients": "Пацієнти",
      "list_patients": "Список пацієнтів",
      "create_patient": "Створити пацієнта",
      "patient_details": "Деталі пацієнта",
      "logout": "Вийти",
      "overview": "Огляд",
      "account": "Обліковий запис"
    },
    "dashboard": {
      "patient_register_success": "Пацієнта успішно зареєстровано.",
      "chatbot_created_success": "Чат-бот успішно створений.",
      "chatbot_named_success": "Чат-бот успішно перейменовано.",
      "chatbot_cloned_success": "Чат-бот успішно клоновано.",
      "chatbot_deleted_success": "Чат-бот успішно видалено.",
      "register_new_patient": "Зареєструвати нового пацієнта",
      "add_patient": "Додати пацієнта",
      "patients": "Пацієнти",
      "patient_id": "ID пацієнта",
      "no_patients_found": "Пацієнтів не знайдено.",
      "new_patient": "Новий пацієнт",
      "enter_information_register_new_patient": "Введіть інформацію для реєстрації нового пацієнта.",
      "patient_name": "Ім'я пацієнта",
      "patient_gender": "Стать",
      "male": "Чоловіча",
      "female": "Жіноча",
      "other": "Інша",
      "patient_age": "Вік",
      "patient_phone_number": "Номер телефону",
      "patient_email": "Електронна пошта",
      "patient_address": "Адреса",
      "patient_description": "Опис пацієнта",
      "cancel": "Скасувати",
      "register": "Зареєструвати",
      "create_new_chatbot_template": "Створити новий шаблон чат-бота",
      "create_bot": "Створити бота",
      "your_chatbot_templates": "Ваші шаблони чат-ботів",
      "unnamed_bot": "Безіменний бот",
      "no_welcome_message_set": "Привітальне повідомлення не встановлено",
      "language": "Мова",
      "role": "Роль",
      "no_chatbots_created_yet": "Ще не створено жодного чат-бота.",
      "rename": "Перейменувати",
      "clone": "Клонувати",
      "delete": "Видалити",
      "save": "Зберегти",
      "new_bot": "Новий бот",
      "what_would_you_like_to_name_your_bot": "Як би ви хотіли назвати свого бота?",
      "enter_bot_name": "Введіть ім'я бота",
      "rename_bot": "Перейменувати бота",
      "enter_new_name_for_bot": "Введіть нове ім'я для вашого бота.",
      "enter_new_bot_name": "Введіть нове ім'я бота",
      "welcome_message": "Ви увійшли як: "
    },
    "not_found": {
      "title": "404 - Сторінку не знайдено",
      "message": "Ой! Сторінка, яку ви шукаєте, не існує."
    },
    "patient_detail": {
      "message": "Це сторінка деталей пацієнта з ID"
    },
    "patient_create": {
      "title": "Це сторінка створення нового пацієнта",
      "new_patient": "Новий пацієнт",
      "create_patient": "Створити пацієнта",
      "patient_name": "Ім'я",
      "patient_age": "Вік",
      "patient_gender": "Стать",
      "male": "Чоловіча",
      "female": "Жіноча",
      "other": "Інша",
      "patient_marital_status": "Сімейний стан",
      "patient_religion": "Релігія",
      "patient_education": "Освіта",
      "patient_occupation": "Професія",
      "patient_income": "Дохід",
      "patient_address": "Адреса",
      "patient_phone": "Телефон",
      "patient_email": "Електронна пошта",
      "patient_date_of_admission": "Дата прийому",
      "register": "Зареєструвати",
      "cancel": "Скасувати",
      "complaint": "Скарга",
      "main_complaints": "Основні скарги",
      "history_of_present_illness": "Історія теперішнього захворювання",
      "hpi_duration": "Тривалість",
      "hpi_onset": "Початок",
      "onset_abrupt": "Раптовий",
      "onset_acute": "Гострий",
      "onset_subacute": "Підгострий",
      "onset_insidious": "Поступовий",
      "hpi_course": "Перебіг",
      "hpi_course_continuous": "Безперервний",
      "hpi_course_episodic": "Епізодичний",
      "hpi_course_fluctuating": "Коливальний",
      "hpi_course_deteriorating": "Погіршувальний",
      "hpi_course_improving": "Покращувальний",
      "hpi_course_unclear": "Незрозумілий",
      "hpi_precipitating_factors": "Фактори, що провокують",
      "hpi_aggravating_relieving": "Обтяжуючі та полегшуючі фактори",
      "hpi_aggravating_relieving_placeholder": "Що полегшує або погіршує стан?",
      "hpi_timeline": "Хронологія симптомів",
      "hpi_timeline_placeholder": "Опишіть, як симптоми змінювалися з часом.",
      "hpi_advanced_details": "Розширена інформація про хворобу",
      "hpi_disturbances": "Порушення сну, апетиту, енергії тощо",
      "hpi_disturbances_placeholder": "наприклад, безсоння, втома, зміна ваги",
      "hpi_suicidal_ideation": "Суїцидальні думки або дії",
      "yes_no_explanation": "Так/Ні з коротким поясненням",
      "hpi_negative_history": "Негативна історія (відсутність симптомів)",
      "hpi_negative_history_placeholder": "Згадайте умови, які не спостерігалися",
      "history_present_illness": "Історія теперішнього захворювання",
      "hpi_general_info": "Загальна інформація",
      "hpi_onset_abrupt": "Раптовий",
      "hpi_onset_acute": "Гострий",
      "hpi_onset_subacute": "Підгострий",
      "hpi_onset_insidious": "Поступовий",
      "hpi_symptom_timeline": "Хронологія симптомів",
      "add_another_complaint": "Додати ще одну скаргу",
      "treatment_history": "Історія лікування",
      "treatment_past": "Минулі лікування",
      "treatment_current": "Поточне лікування",
      "past_history": "Медична історія",
      "past_medical": "Минулі медичні захворювання",
      "past_psych": "Минулі психіатричні захворювання",
      "family_history": "Сімейна історія",
      "family_illness": "Сімейні захворювання",
      "family_social": "Сімейне соціальне середовище",
      "personal_history": "Особиста історія",
      "personal_perinatal": "Перинатальний період",
      "personal_childhood": "Дитинство",
      "personal_education": "Освіта",
      "personal_play": "Гра та соціальні відносини",
      "personal_adolescence": "Підлітковий період",
      "personal_puberty": "Статеве дозрівання",
      "personal_obstetric": "Акушерська історія",
      "personal_occupational": "Професійна діяльність",
      "personal_marital": "Шлюб та стосунки",
      "personal_premorbid": "Преморбідна особистість",
      "patient_register_success": "Пацієнта успішно зареєстровано.",
      "patient_register_failed": "Не вдалося зареєструвати пацієнта. Спробуйте ще раз."
    },
    "register": {
      "register_therapist": "Зареєструвати терапевта",
      "email": "Електронна пошта",
      "password": "Пароль",
      "register": "Зареєструвати"
    },
    "login": {
      "login_therapist": "Увійти як терапевт",
      "email": "Електронна пошта",
      "password": "Пароль",
      "login": "Увійти"
    }
  }
}

export default Resources;
