package ch.uzh.ifi.imrg.platform.constant;

public enum LogTypes {
    JOURNAL_CREATION,
    JOURNAL_UPDATE,
    EXERCISE_START,
    EXERCISE_COMPLETION,
    EXERCISE_UPDATE,
    GENERAL_CONVERSATION_CREATION,
    GENERAL_CONVERSATION_NAME_UPDATE,
    GENERAL_CONVERSATION_MESSAGE_CREATION,
    DOCUMENT_CONVERSATION_MESSAGE_CREATION,
    EXERCISE_CONVERSATION_MESSAGE_CREATION,
    JOURNAL_CONVERSATION_MESSAGE_CREATION,
    CHATBOT_ICON_UPDATE,
    HARMFUL_CONTENT_DETECTED,
    DOCUMENT_READ,
    PSYCHOLOGICAL_TEST_COMPLETED,
}