/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChatbotTemplateOutputDTO
 */
export interface ChatbotTemplateOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotIcon'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotLanguage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotRole'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotTone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'welcomeMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotVoice'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotGender'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'preConfiguredExercise'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'additionalExercise'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'animation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'chatbotInputPlaceholder'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    'therapistId'?: string;
}

