/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatbotTemplateOutputDTO
 */
export interface ChatbotTemplateOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotName?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotModel?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotIcon?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotRole?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    chatbotTone?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    welcomeMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatbotTemplateOutputDTO
     */
    workspaceId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatbotTemplateOutputDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChatbotTemplateOutputDTO
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ChatbotTemplateOutputDTO interface.
 */
export function instanceOfChatbotTemplateOutputDTO(value: object): value is ChatbotTemplateOutputDTO {
    return true;
}

export function ChatbotTemplateOutputDTOFromJSON(json: any): ChatbotTemplateOutputDTO {
    return ChatbotTemplateOutputDTOFromJSONTyped(json, false);
}

export function ChatbotTemplateOutputDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatbotTemplateOutputDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'chatbotName': json['chatbotName'] == null ? undefined : json['chatbotName'],
        'description': json['description'] == null ? undefined : json['description'],
        'chatbotModel': json['chatbotModel'] == null ? undefined : json['chatbotModel'],
        'chatbotIcon': json['chatbotIcon'] == null ? undefined : json['chatbotIcon'],
        'chatbotLanguage': json['chatbotLanguage'] == null ? undefined : json['chatbotLanguage'],
        'chatbotRole': json['chatbotRole'] == null ? undefined : json['chatbotRole'],
        'chatbotTone': json['chatbotTone'] == null ? undefined : json['chatbotTone'],
        'welcomeMessage': json['welcomeMessage'] == null ? undefined : json['welcomeMessage'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ChatbotTemplateOutputDTOToJSON(json: any): ChatbotTemplateOutputDTO {
    return ChatbotTemplateOutputDTOToJSONTyped(json, false);
}

export function ChatbotTemplateOutputDTOToJSONTyped(value?: ChatbotTemplateOutputDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chatbotName': value['chatbotName'],
        'description': value['description'],
        'chatbotModel': value['chatbotModel'],
        'chatbotIcon': value['chatbotIcon'],
        'chatbotLanguage': value['chatbotLanguage'],
        'chatbotRole': value['chatbotRole'],
        'chatbotTone': value['chatbotTone'],
        'welcomeMessage': value['welcomeMessage'],
        'workspaceId': value['workspaceId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

