/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChatMessageDTO
 */
export interface ChatMessageDTO {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    'chatRole'?: ChatMessageDTOChatRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    'content'?: string;
}

export const ChatMessageDTOChatRoleEnum = {
    User: 'USER',
    Assistant: 'ASSISTANT',
    System: 'SYSTEM'
} as const;

export type ChatMessageDTOChatRoleEnum = typeof ChatMessageDTOChatRoleEnum[keyof typeof ChatMessageDTOChatRoleEnum];


