/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoachJournalEntryOutputDTOPatientAPI
 */
export interface CoachJournalEntryOutputDTOPatientAPI {
    /**
     * 
     * @type {string}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'content'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof CoachJournalEntryOutputDTOPatientAPI
     */
    'tags'?: Set<string>;
}

