/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ComplaintDTO
 */
export interface ComplaintDTO {
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'mainComplaint'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'duration'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'onset'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'course'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'precipitatingFactors'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'aggravatingRelieving'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'timeline'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'disturbances'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'suicidalIdeation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDTO
     */
    'negativeHistory'?: string;
}

