/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CounselingPlanExerciseAIGeneratedOutputDTO
 */
export interface CounselingPlanExerciseAIGeneratedOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanExerciseAIGeneratedOutputDTO
     */
    'selectedMeetingId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanExerciseAIGeneratedOutputDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanExerciseAIGeneratedOutputDTO
     */
    'exerciseType'?: CounselingPlanExerciseAIGeneratedOutputDTOExerciseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanExerciseAIGeneratedOutputDTO
     */
    'exerciseStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanExerciseAIGeneratedOutputDTO
     */
    'exerciseEnd'?: string;
}

export const CounselingPlanExerciseAIGeneratedOutputDTOExerciseTypeEnum = {
    Journaling: 'JOURNALING',
    Breathing: 'BREATHING',
    Other: 'OTHER'
} as const;

export type CounselingPlanExerciseAIGeneratedOutputDTOExerciseTypeEnum = typeof CounselingPlanExerciseAIGeneratedOutputDTOExerciseTypeEnum[keyof typeof CounselingPlanExerciseAIGeneratedOutputDTOExerciseTypeEnum];


