/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CounselingPlanPhaseGoalOutputDTO } from './counseling-plan-phase-goal-output-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseOutputDTO } from './exercise-output-dto';

/**
 * 
 * @export
 * @interface CounselingPlanPhaseOutputDTO
 */
export interface CounselingPlanPhaseOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'phaseName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'endDate'?: string;
    /**
     * 
     * @type {Array<ExerciseOutputDTO>}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'phaseExercisesOutputDTO'?: Array<ExerciseOutputDTO>;
    /**
     * 
     * @type {Array<CounselingPlanPhaseGoalOutputDTO>}
     * @memberof CounselingPlanPhaseOutputDTO
     */
    'phaseGoalsOutputDTO'?: Array<CounselingPlanPhaseGoalOutputDTO>;
}

