/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CounselingPlanPhaseGoalOutputDTO
 */
export interface CounselingPlanPhaseGoalOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseGoalOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseGoalOutputDTO
     */
    'goalName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselingPlanPhaseGoalOutputDTO
     */
    'goalDescription'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CounselingPlanPhaseGoalOutputDTO
     */
    'isCompleted'?: boolean;
}

