/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePatientDTO
 */
export interface CreatePatientDTO {
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'gender'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePatientDTO
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePatientDTO
     */
    'description'?: string;
}

