/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTherapySessionDTO
 */
export interface CreateTherapySessionDTO {
    /**
     * 
     * @type {Date}
     * @memberof CreateTherapySessionDTO
     */
    sessionStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateTherapySessionDTO
     */
    sessionEnd?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateTherapySessionDTO
     */
    patientId?: string;
}

/**
 * Check if a given object implements the CreateTherapySessionDTO interface.
 */
export function instanceOfCreateTherapySessionDTO(value: object): value is CreateTherapySessionDTO {
    return true;
}

export function CreateTherapySessionDTOFromJSON(json: any): CreateTherapySessionDTO {
    return CreateTherapySessionDTOFromJSONTyped(json, false);
}

export function CreateTherapySessionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTherapySessionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionStart': json['sessionStart'] == null ? undefined : (new Date(json['sessionStart'])),
        'sessionEnd': json['sessionEnd'] == null ? undefined : (new Date(json['sessionEnd'])),
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
    };
}

export function CreateTherapySessionDTOToJSON(json: any): CreateTherapySessionDTO {
    return CreateTherapySessionDTOToJSONTyped(json, false);
}

export function CreateTherapySessionDTOToJSONTyped(value?: CreateTherapySessionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionStart': value['sessionStart'] == null ? undefined : ((value['sessionStart']).toISOString()),
        'sessionEnd': value['sessionEnd'] == null ? undefined : ((value['sessionEnd']).toISOString()),
        'patientId': value['patientId'],
    };
}

