/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateChatbotTemplateDTO
 */
export interface CreateChatbotTemplateDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateChatbotTemplateDTO
     */
    'chatbotName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatbotTemplateDTO
     */
    'chatbotIcon'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatbotTemplateDTO
     */
    'chatbotRole'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatbotTemplateDTO
     */
    'chatbotTone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatbotTemplateDTO
     */
    'welcomeMessage'?: string;
}

