/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCounselingPlanExerciseAIGeneratedDTO
 */
export interface CreateCounselingPlanExerciseAIGeneratedDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateCounselingPlanExerciseAIGeneratedDTO
     */
    'counselingPlanPhaseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCounselingPlanExerciseAIGeneratedDTO
     */
    'language'?: CreateCounselingPlanExerciseAIGeneratedDTOLanguageEnum;
}

export const CreateCounselingPlanExerciseAIGeneratedDTOLanguageEnum = {
    English: 'English',
    Ukrainian: 'Ukrainian',
    German: 'German'
} as const;

export type CreateCounselingPlanExerciseAIGeneratedDTOLanguageEnum = typeof CreateCounselingPlanExerciseAIGeneratedDTOLanguageEnum[keyof typeof CreateCounselingPlanExerciseAIGeneratedDTOLanguageEnum];


