/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateExerciseDTO
 */
export interface CreateExerciseDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseDTO
     */
    'exerciseTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseDTO
     */
    'exerciseDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseDTO
     */
    'exerciseExplanation'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseDTO
     */
    'exerciseStart'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateExerciseDTO
     */
    'durationInWeeks'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateExerciseDTO
     */
    'doEveryNDays'?: number;
}

