/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateExerciseComponentDTO
 */
export interface CreateExerciseComponentDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseComponentDTO
     */
    'exerciseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseComponentDTO
     */
    'exerciseComponentDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseComponentDTO
     */
    'exerciseComponentType'?: CreateExerciseComponentDTOExerciseComponentTypeEnum;
}

export const CreateExerciseComponentDTOExerciseComponentTypeEnum = {
    Text: 'TEXT',
    InputFieldPrivate: 'INPUT_FIELD_PRIVATE',
    InputFieldShared: 'INPUT_FIELD_SHARED',
    File: 'FILE',
    Image: 'IMAGE',
    YoutubeVideo: 'YOUTUBE_VIDEO'
} as const;

export type CreateExerciseComponentDTOExerciseComponentTypeEnum = typeof CreateExerciseComponentDTOExerciseComponentTypeEnum[keyof typeof CreateExerciseComponentDTOExerciseComponentTypeEnum];


