/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseComponentOutputDTO } from './exercise-component-output-dto';

/**
 * 
 * @export
 * @interface ExerciseOutputDTO
 */
export interface ExerciseOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'exerciseTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'exerciseDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'exerciseExplanation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'exerciseStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOutputDTO
     */
    'exerciseEnd'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExerciseOutputDTO
     */
    'isPaused'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExerciseOutputDTO
     */
    'doEveryNDays'?: number;
    /**
     * 
     * @type {Array<ExerciseComponentOutputDTO>}
     * @memberof ExerciseOutputDTO
     */
    'exerciseComponentsOutputDTO'?: Array<ExerciseComponentOutputDTO>;
}

