/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseMoodOutputDTOPatientAPI } from './exercise-mood-output-dtopatient-api';

/**
 * 
 * @export
 * @interface ExerciseInformationOutputDTOPatientAPI
 */
export interface ExerciseInformationOutputDTOPatientAPI {
    /**
     * 
     * @type {string}
     * @memberof ExerciseInformationOutputDTOPatientAPI
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseInformationOutputDTOPatientAPI
     */
    'endTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseInformationOutputDTOPatientAPI
     */
    'feedback'?: string;
    /**
     * 
     * @type {Array<ExerciseMoodOutputDTOPatientAPI>}
     * @memberof ExerciseInformationOutputDTOPatientAPI
     */
    'moodsBefore'?: Array<ExerciseMoodOutputDTOPatientAPI>;
    /**
     * 
     * @type {Array<ExerciseMoodOutputDTOPatientAPI>}
     * @memberof ExerciseInformationOutputDTOPatientAPI
     */
    'moodsAfter'?: Array<ExerciseMoodOutputDTOPatientAPI>;
}

