/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExerciseComponentOutputDTO
 */
export interface ExerciseComponentOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'exerciseComponentType'?: ExerciseComponentOutputDTOExerciseComponentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'exerciseComponentDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'fileType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseComponentOutputDTO
     */
    'extractedText'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExerciseComponentOutputDTO
     */
    'orderNumber'?: number;
}

export const ExerciseComponentOutputDTOExerciseComponentTypeEnum = {
    Text: 'TEXT',
    InputFieldPrivate: 'INPUT_FIELD_PRIVATE',
    InputFieldShared: 'INPUT_FIELD_SHARED',
    File: 'FILE',
    Image: 'IMAGE',
    YoutubeVideo: 'YOUTUBE_VIDEO'
} as const;

export type ExerciseComponentOutputDTOExerciseComponentTypeEnum = typeof ExerciseComponentOutputDTOExerciseComponentTypeEnum[keyof typeof ExerciseComponentOutputDTOExerciseComponentTypeEnum];


