/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GAD7TestOutputDTO
 */
export interface GAD7TestOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof GAD7TestOutputDTO
     */
    'testId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GAD7TestOutputDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GAD7TestOutputDTO
     */
    'meetingId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GAD7TestOutputDTO
     */
    'creationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question1'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question2'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question3'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question4'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question5'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question6'?: number;
    /**
     * 
     * @type {number}
     * @memberof GAD7TestOutputDTO
     */
    'question7'?: number;
}

