/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogOutputDTO
 */
export interface LogOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'logType'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'uniqueIdentifier'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogOutputDTO
     */
    'comment'?: string;
}

