/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MeetingNoteOutputDTO } from './meeting-note-output-dto';

/**
 * 
 * @export
 * @interface MeetingOutputDTO
 */
export interface MeetingOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof MeetingOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingOutputDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingOutputDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingOutputDTO
     */
    'meetingStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingOutputDTO
     */
    'meetingEnd'?: string;
    /**
     * 
     * @type {Array<MeetingNoteOutputDTO>}
     * @memberof MeetingOutputDTO
     */
    'meetingNotesOutputDTO'?: Array<MeetingNoteOutputDTO>;
}

