/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MeetingOutputDTO } from './meeting-output-dto';

/**
 * 
 * @export
 * @interface PatientOutputDTO
 */
export interface PatientOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'gender'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatientOutputDTO
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'maritalStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'religion'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'education'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'occupation'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'income'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'dateOfAdmission'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'personalHistory'?: string;
    /**
     * 
     * @type {Array<MeetingOutputDTO>}
     * @memberof PatientOutputDTO
     */
    'meetingsOutputDTO'?: Array<MeetingOutputDTO>;
}

