/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TherapySessionOutputDTO } from './TherapySessionOutputDTO'
import {
  TherapySessionOutputDTOFromJSON,
  TherapySessionOutputDTOFromJSONTyped,
  TherapySessionOutputDTOToJSON,
  TherapySessionOutputDTOToJSONTyped,
} from './TherapySessionOutputDTO'

/**
 *
 * @export
 * @interface PatientOutputDTO
 */
export interface PatientOutputDTO {
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  name?: string
  /**
   *
   * @type {Date}
   * @memberof PatientOutputDTO
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof PatientOutputDTO
   */
  updatedAt?: Date
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  phoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  address?: string
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  gender?: string
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  description?: string
  /**
   *
   * @type {number}
   * @memberof PatientOutputDTO
   */
  age?: number
  /**
   *
   * @type {string}
   * @memberof PatientOutputDTO
   */
  email?: string
  /**
   *
   * @type {Array<TherapySessionOutputDTO>}
   * @memberof PatientOutputDTO
   */
  therapySessionsOutputDTO?: Array<TherapySessionOutputDTO>
}

/**
 * Check if a given object implements the PatientOutputDTO interface.
 */
export function instanceOfPatientOutputDTO(value: object): value is PatientOutputDTO {
  return true
}

export function PatientOutputDTOFromJSON(json: any): PatientOutputDTO {
  return PatientOutputDTOFromJSONTyped(json, false)
}

export function PatientOutputDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatientOutputDTO {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
    phoneNumber: json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    address: json['address'] == null ? undefined : json['address'],
    gender: json['gender'] == null ? undefined : json['gender'],
    description: json['description'] == null ? undefined : json['description'],
    age: json['age'] == null ? undefined : json['age'],
    email: json['email'] == null ? undefined : json['email'],
    therapySessionsOutputDTO:
      json['therapySessionsOutputDTO'] == null
        ? undefined
        : (json['therapySessionsOutputDTO'] as Array<any>).map(TherapySessionOutputDTOFromJSON),
  }
}

export function PatientOutputDTOToJSON(json: any): PatientOutputDTO {
  return PatientOutputDTOToJSONTyped(json, false)
}

export function PatientOutputDTOToJSONTyped(
  value?: PatientOutputDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    createdAt: value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
    phoneNumber: value['phoneNumber'],
    address: value['address'],
    gender: value['gender'],
    description: value['description'],
    age: value['age'],
    email: value['email'],
    therapySessionsOutputDTO:
      value['therapySessionsOutputDTO'] == null
        ? undefined
        : (value['therapySessionsOutputDTO'] as Array<any>).map(TherapySessionOutputDTOToJSON),
  }
}
