/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PsychologicalTestCreateDTO
 */
export interface PsychologicalTestCreateDTO {
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestCreateDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestCreateDTO
     */
    'testName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestCreateDTO
     */
    'exerciseStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestCreateDTO
     */
    'exerciseEnd'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PsychologicalTestCreateDTO
     */
    'isPaused'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PsychologicalTestCreateDTO
     */
    'doEveryNDays'?: number;
}

