/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PsychologicalTestQuestionOutputDTO } from './psychological-test-question-output-dto';

/**
 * 
 * @export
 * @interface PsychologicalTestOutputDTO
 */
export interface PsychologicalTestOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestOutputDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestOutputDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestOutputDTO
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PsychologicalTestOutputDTO
     */
    'completedAt'?: string;
    /**
     * 
     * @type {Array<PsychologicalTestQuestionOutputDTO>}
     * @memberof PsychologicalTestOutputDTO
     */
    'questions'?: Array<PsychologicalTestQuestionOutputDTO>;
}

