/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateExerciseDTO
 */
export interface UpdateExerciseDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateExerciseDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExerciseDTO
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExerciseDTO
     */
    'exerciseType'?: UpdateExerciseDTOExerciseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateExerciseDTO
     */
    'exerciseStart'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateExerciseDTO
     */
    'exerciseEnd'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateExerciseDTO
     */
    'isPaused'?: boolean;
}

export const UpdateExerciseDTOExerciseTypeEnum = {
    Journaling: 'JOURNALING',
    Breathing: 'BREATHING',
    Other: 'OTHER'
} as const;

export type UpdateExerciseDTOExerciseTypeEnum = typeof UpdateExerciseDTOExerciseTypeEnum[keyof typeof UpdateExerciseDTOExerciseTypeEnum];


