// This file is auto-generated by scripts/generate-translations.ts

export interface Translations {
  header: {
    title: string;
    subtitle: string;
    dashboard: string;
    register: string;
    login: string;
    patients: string;
    patient_detail: string;
    patient_create_bot: string;
    bot_edit: string;
    create_bot_template: string;
    edit_bot_template: string;
    settings: string;
  },
  footer: {
    title: string;
  },
  settings: {
    title: string;
    language: string;
  },
  layout: {
    dashboard: string;
    dashboards: string;
    logout: string;
    overview: string;
    account: string;
  },
  dashboard: {
    patient_register_success: string;
    chatbot_created_success: string;
    chatbot_named_success: string;
    chatbot_cloned_success: string;
    chatbot_deleted_success: string;
    register_new_patient: string;
    add_patient: string;
    patients: string;
    patient_id: string;
    no_patients_found: string;
    new_patient: string;
    enter_information_register_new_patient: string;
    patient_name: string;
    cancel: string;
    register: string;
    create_new_chatbot_template: string;
    create_bot: string;
    your_chatbot_templates: string;
    unnamed_bot: string;
    no_welcome_message_set: string;
    language: string;
    role: string;
    no_chatbots_created_yet: string;
    rename: string;
    clone: string;
    delete: string;
    save: string;
    new_bot: string;
    what_would_you_like_to_name_your_bot: string;
    enter_bot_name: string;
    rename_bot: string;
    enter_new_name_for_bot: string;
    enter_new_bot_name: string;
  },
  not_found: {
    404: string;
    message: string;
  },
  patient_detail: {
    message: string;
  },
  register: {
    register_therapist: string;
    email: string;
    password: string;
    register: string;
  },
}
