resources:
  - ../../../base/backend

namespace: therapist-app-production

images:
  - name: jonasblum/therapist-app-backend-production
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-backend-ingress
    path: patch-ingress.json
