resources:
  - ../../../base/backend
  - namespace.yaml

namespace: therapist-app-production

configMapGenerator:
  - name: therapist-app-backend-config
    literals:
      - DB_HOST=192.168.1.147
      - DB_PORT=5432
      - DB_NAME=therapist_app_production_db
      - DB_USERNAME=therapist-user

secretGenerator:
  - name: therapist-app-backend-secret
    envs:
      - env.secrets
    type: Opaque

images:
  - name: jonasblum/image-to-be-replaced-depending-on-environment
    newName: jonasblum/therapist-app-backend-production
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: therapist-app-backend-ingress
    path: patch-ingress.json
