apiVersion: apps/v1
kind: Deployment
metadata:
  name: therapist-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: therapist-app-backend
  template:
    metadata:
      labels:
        app: therapist-app-backend
    spec:
      containers:
        - name: therapist-app-backend
          image: jonasblum/therapist-app-backend-main # Default image, overridden in overlays
          ports:
            - containerPort: 8080
