name: Build and Deploy

on:
  push:
    branches:
      - main
      - production

jobs:
  build-and-restart:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "FRONTEND_IMAGE=jonasblum/therapist-app-frontend-main:latest" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/therapist-app-backend-main:latest" >> $GITHUB_ENV
            echo "FRONTEND_DEPLOYMENT=therapist-fe-m" >> $GITHUB_ENV
            echo "BACKEND_DEPLOYMENT=therapist-be-m" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "BRANCH=production" >> $GITHUB_ENV
            echo "FRONTEND_IMAGE=jonasblum/therapist-app-frontend-production:latest" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/therapist-app-backend-production:latest" >> $GITHUB_ENV
            echo "FRONTEND_DEPLOYMENT=therapist-fe-p" >> $GITHUB_ENV
            echo "BACKEND_DEPLOYMENT=therapist-be-p" >> $GITHUB_ENV
          fi

      - name: Build and Push Frontend Image (Standard Docker)
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }} frontend/.
          docker push ${{ env.FRONTEND_IMAGE }}

      - name: Build and Push Backend Image (Standard Docker)
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }} backend/.
          docker push ${{ env.BACKEND_IMAGE }}

      - name: Restart Kubernetes Deployments
        run: |
          kubectl set image deployment/${{ env.FRONTEND_DEPLOYMENT }} ${{ env.FRONTEND_DEPLOYMENT }}=${{ env.FRONTEND_IMAGE }}
          kubectl set image deployment/${{ env.BACKEND_DEPLOYMENT }} ${{ env.BACKEND_DEPLOYMENT }}=${{ env.BACKEND_IMAGE }}
          kubectl rollout restart deployment/${{ env.FRONTEND_DEPLOYMENT }}
          kubectl rollout restart deployment/${{ env.BACKEND_DEPLOYMENT }}
