name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-restart:
    runs-on: [self-hosted, k3s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then

            echo "BRANCH=main" >> $GITHUB_ENV
            echo "FRONTEND_IMAGE=jonasblum/therapist-app-frontend-main:latest" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/therapist-app-backend-main:latest" >> $GITHUB_ENV
          fi

      - name: Build Images for Frontend and Backend
        run: |
          docker build --build-arg ENV_NAME=${{ env.BRANCH }} -t ${{ env.FRONTEND_IMAGE }} frontend/.
          docker build -t ${{ env.BACKEND_IMAGE }} backend/.

      - name: Push Images for Frontend and Backend
        run: |
          docker push ${{ env.FRONTEND_IMAGE }}
          docker push ${{ env.BACKEND_IMAGE }}

      - name: Restart Kubernetes Deployments
        env:
          DB_PASSWORD_MAIN: ${{ secrets.DB_PASSWORD_MAIN }}
          JWT_SECRET_KEY_MAIN: ${{ secrets.JWT_SECRET_KEY_MAIN }}
          CHAT_GPT_API_KEY: ${{secrets.CHAT_GPT_API_KEY}}
          LOCAL_LLM_API_KEY: ${{ secrets.LOCAL_LLM_API_KEY }}
          COACH_ACCESS_KEY_MAIN: ${{secrets.COACH_ACCESS_KEY_MAIN}}
          AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
          AZURE_OPENAI_API_KEY: ${{secrets.AZURE_OPENAI_API_KEY}}

        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            
            echo "DB_PASSWORD=$DB_PASSWORD_MAIN" > .kubernetes/overlays/main/backend/env.secrets
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY_MAIN" >> .kubernetes/overlays/main/backend/env.secrets
            echo "CHAT_GPT_API_KEY=$CHAT_GPT_API_KEY" >> .kubernetes/overlays/main/backend/env.secrets
            echo "LOCAL_LLM_API_KEY=$LOCAL_LLM_API_KEY" >> .kubernetes/overlays/main/backend/env.secrets
            echo "COACH_ACCESS_KEY=$COACH_ACCESS_KEY_MAIN" >> .kubernetes/overlays/main/backend/env.secrets
            echo "AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT" >> .kubernetes/overlays/main/backend/env.secrets
            echo "AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY" >> .kubernetes/overlays/main/backend/env.secrets
            
            kubectl apply -k .kubernetes/overlays/main/backend
            kubectl apply -k .kubernetes/overlays/main/frontend

            kubectl rollout restart deployment/therapist-app-backend -n therapist-app-main
            kubectl rollout restart deployment/therapist-app-frontend -n therapist-app-main
          fi
