name: Build and Deploy

on:
  push:
    branches:
      - main
      - production

jobs:
  build-and-restart:
    runs-on: [self-hosted, k3s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then

            echo "BRANCH=main" >> $GITHUB_ENV
            echo "FRONTEND_IMAGE=jonasblum/therapist-app-frontend-main:latest" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/therapist-app-backend-main:latest" >> $GITHUB_ENV

          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then

            echo "BRANCH=production" >> $GITHUB_ENV
            echo "FRONTEND_IMAGE=jonasblum/therapist-app-frontend-production:latest" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/therapist-app-backend-production:latest" >> $GITHUB_ENV

          fi

      - name: Build Images for Frontend and Backend
        run: |
          docker build --build-arg ENV_NAME=${{ env.BRANCH }} -t ${{ env.FRONTEND_IMAGE }} frontend/.
          docker build -t ${{ env.BACKEND_IMAGE }} backend/.

      - name: Push Images for Frontend and Backend
        run: |
          docker push ${{ env.FRONTEND_IMAGE }}
          docker push ${{ env.BACKEND_IMAGE }}

      - name: Restart Kubernetes Deployments
        env:
          DB_PASSWORD_MAIN: ${{ secrets.DB_PASSWORD_MAIN }}
          DB_PASSWORD_PRODUCTION: ${{ secrets.DB_PASSWORD_PRODUCTION }}
          JWT_SECRET_KEY_MAIN: ${{ secrets.JWT_SECRET_KEY_MAIN }}
          JWT_SECRET_KEY_PRODUCTION: ${{ secrets.JWT_SECRET_KEY_PRODUCTION }}
          CHAT_GPT_API_KEY: ${{secrets.CHAT_GPT_API_KEY}}
          LOCAL_LLM_API_KEY: ${{ secrets.LOCAL_LLM_API_KEY }}

        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            
            echo "DB_PASSWORD=$DB_PASSWORD_MAIN" > .kubernetes/overlays/main/backend/env.secrets
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY_MAIN" >> .kubernetes/overlays/main/backend/env.secrets
            echo "CHAT_GPT_API_KEY=$CHAT_GPT_API_KEY" >> .kubernetes/overlays/main/backend/env.secrets
            echo "LOCAL_LLM_API_KEY=$LOCAL_LLM_API_KEY" >> .kubernetes/overlays/main/backend/env.secrets
            
            kubectl apply -k .kubernetes/overlays/main/backend
            kubectl apply -k .kubernetes/overlays/main/frontend

            kubectl rollout restart deployment/therapist-app-backend -n therapist-app-main
            kubectl rollout restart deployment/therapist-app-frontend -n therapist-app-main

          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then 
            
            echo "DB_PASSWORD=$DB_PASSWORD_PRODUCTION" > .kubernetes/overlays/production/backend/env.secrets
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY_PRODUCTION" >> .kubernetes/overlays/production/backend/env.secrets
            echo "CHAT_GPT_API_KEY=$CHAT_GPT_API_KEY" >> .kubernetes/overlays/production/backend/env.secrets
            echo "LOCAL_LLM_API_KEY=$LOCAL_LLM_API_KEY" >> .kubernetes/overlays/production/backend/env.secrets
            
            kubectl apply -k .kubernetes/overlays/production/backend
            kubectl apply -k .kubernetes/overlays/production/frontend

            kubectl rollout restart deployment/therapist-app-backend -n therapist-app-production
            kubectl rollout restart deployment/therapist-app-frontend -n therapist-app-production
            
          fi
