name: PR Checks

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  frontend-lint-and-typecheck:
    name: Run Type Checking, Linting, and Prettier
    runs-on: self-hosted
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Linting
        run: |
          cd frontend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd frontend
          npm run format

  backend-format-check:
    name: Check Java Formatting
    runs-on: self-hosted
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run Formatting Check
        run: |
          cd backend
          ./gradlew spotlessCheck

  sonarcloud-frontend:
    name: SonarCloud Analysis (Frontend)
    runs-on: ubuntu-latest
    needs: [frontend-lint-and-typecheck, backend-format-check]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonarcloud-backend:
    name: SonarCloud Analysis (Backend)
    runs-on: ubuntu-latest
    needs: [frontend-lint-and-typecheck, backend-format-check]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for better analysis

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd backend
          ./gradlew build sonar --info

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: self-hosted
    needs: [frontend-lint-and-typecheck, backend-format-check, sonarcloud-frontend, sonarcloud-backend]
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Image with Cache
        run: docker build -t frontend-test-build ./frontend

  build-backend:
    name: Build Backend Docker Image
    runs-on: self-hosted
    needs: [frontend-lint-and-typecheck, backend-format-check, sonarcloud-frontend, sonarcloud-backend]
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image with Cache
        run: docker build -t backend-test-build ./backend
