name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-lint-and-typecheck:
    name: Run Type Checking, Linting, and Prettier
    runs-on: self-hosted
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Linting
        run: |
          cd frontend
          npm run lint

      - name: Run Prettier Check
        run: |
          cd frontend
          npm run format

  backend-format-check:
    name: Check Java Formatting
    runs-on: self-hosted
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run Formatting Check
        run: |
          cd backend
          ./gradlew spotlessCheck

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: self-hosted
    needs: [frontend-lint-and-typecheck]
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Image with Cache
        run: docker build -t frontend-test-build ./frontend

  build-backend:
    name: Build Backend Docker Image
    runs-on: self-hosted
    needs: [backend-format-check]
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image with Cache
        run: docker build -t backend-test-build ./backend
